
:doctype: book
:toc: left
:toclevels: 3

== Asciidoctor 

=== Installation

Since we want to create output formats directly from 
and into our repository we can use the 
link:https://docs.asciidoctor.org/maven-tools/latest[Asciidoctor Maven Tools].

We are still in the prototyping phase of the project and the first step was to write `.adoc` files. 
So we want to link the files accross the whole project and keep it simple.
Therefore we will use the 
link:https://docs.asciidoctor.org/maven-tools/latest/plugin/introduction/[asciidoctor-maven-plugin]

[quote, see https://docs.asciidoctor.org/maven-tools/latest/plugin/introduction/]
____
The Asciidoctor Maven Plugin is used to convert AsciiDoc documents using Asciidoctor. 
The plugin offers a comprehensive way to configure a conversion process using AsciidoctorJ in a declarative way.
____

=== Introduction

As of `v1.1.x` this repository is in prototyping mode.
Usually developers do a lot of research, trial and error 
or even switch the strategy when realizing a wrong approach.
This important information - mostly for developer him/herself -
and usually scribbled in some (paper) notebook.

We have started out to add a `readme.adoc` on the top level of each project.
The next step is to add graphs for a faster perception of the software.
Also, we want to provide a browsing experience for people interested.
Therefor we picked a modern word processor to gather documents for different output formats.

On the other hand we _do not_ want to create an isolated website for this repository.
The develpment process should remain as straight forward as possible.
That is why we want each projects documentation (sources) in the project 
for the developer to scribble his approaches, progress 
and finally the cleaned result.

One advantage of a multi module project is
that you can open each project separaretly in the IDE
and we want to enable developers to type whenever they feel like it,
or want to get it out of their heads.
This can be done with the adoc files.

Then again you can never be sure _how_ you are looking at the files 
and _where_ they actually reside in the build process.
An asciidoc viewer can be installed in a browser or the IDE etc.
Or the website, like github, already provides the conversion.

This ambiguation is described in the main 
link:../../../../readme.adoc[`readme.adoc`] 
file, where the reader can make a choice between raw/rendered `adoc`,
and between raw/hosted `html` files.
 

To reduce the confusion the `asciidoctor-maven-plugin` is configured 
for the complete build process from reactor to sub/sub .. projects.

=== Configuration

Note that the plugin is defined in the reactor- and not the parent pom.xml! +

[source,xml]
----
<groupId>org.asciidoctor</groupId>
<artifactId>asciidoctor-maven-plugin</artifactId>
<version>3.1.1</version>
<!-- asciidoctor-maven-plugin:3.2.0 requires Maven version 3.8.8 -->
<executions>
    <execution>
        <id>generate-html-docs</id>
        <phase>generate-resources</phase>  // maybe use 'prepare-package'
        <goals>
            <goal>process-asciidoc</goal>
        </goals>
        <configuration>
            <sourceDirectory>${project.basedir}/src/asciidoc</sourceDirectory>
            <outputDirectory>${project.basedir}/src/asciidoc</outputDirectory>
            <backend>html5</backend>
            ...
        </configuration>
    </execution>
</executions>
----

The reason we placed the plugin on top level
is that we also want to create documentation on this level.
Note that we have hard coded `html5` as output format.
This can be changed or widend to pdf and more as required.

Note that a project with `<packaging>pom</packaging>` fetches content from other modules,
but does not compile sources nor create a _primary_ artifact, like a `jar`.
Anyhow it can execute plugins and can create _secondary_ artifacts 
like a `subproject-a-1.1.8-asciidoc.zip`.

In order to find the documentation at the same place in each project
we have defined a general source folder with 

    <sourceDirectory>${project.basedir}/src/asciidoc</sourceDirectory>

For an isolated run you can run

    mvn clean package


==== ! antipattern !

You might have noted the configuration of identical folders for source and output

[source,xml]
----
        <configuration>
            <sourceDirectory>${project.basedir}/src/asciidoc</sourceDirectory>
            <outputDirectory>${project.basedir}/src/asciidoc</outputDirectory>
----

We have done this for simplicity to generate the `html` output right next to the `adoc` source file
in order to conserve the links in the documentation.
Note that we do not use `link` but the `xref` macro to reference documents!
This ensures that you can navigate through  `html` and `adoc` file independantly,
while the developer can change the suffix in the browser url to switch.

Upgrade! +
The html generation should now work without compilation changes, 
like dates, and reproduce previous `*.html` output.
Much better for versioning `;)`


[WARNING]
====
While possible, generating output files directly into your source directory (src/) 
is considered a strong anti-pattern in Maven and software development 
for several critical reasons:

- Mixing Sources and Generated Files: +
Your src directory should only contain human-written source code and resources.

- Version Control Pollution: +
You will have to constantly update your .gitignore file to exclude all generated .html files.

- Build Lifecycle Issues: +
The mvn clean command is designed to delete the target directory. 
It will not touch your src folder. 
This means old, stale HTML files will be left behind, leading to confusion 
and potential errors unless you delete them manually every time.
====

Therefor you should `.gitignore` all html files (or mark 'assume unchanged')
in the folders `${project.basedir}/src/asciidoc` for the time being.
If you don't touch the documentation there is no need to commit the changed html files.

The final section of the `<configuration>` makes sure that sources are adoc 
and output is html without causing confusion:

[source,xml]
----
        <configuration>
            ...
            <sourceDocumentExtensions>
                <sourceDocumentExtension>adoc</sourceDocumentExtension>
            </sourceDocumentExtensions>
            <resources>
                <resource>
                    <directory>${project.basedir}/src/asciidoc</directory>
                    <excludes>
                        <exclude>**/*.html</exclude>
                    </excludes>
                </resource>
            </resources>
        </configuration>
----

==== `<attributes>`

For the time being _we have not_ attributed the ascii documents globally from Maven:

    <attributes>
        <doctype>book</doctype>
        <toc>left</toc>
        <source-highlighter>coderay</source-highlighter>
    </attributes>

but we are experimenting directly in selected adocs:

    :doctype: book
    :toc: left
    :toclevels: 3


=== Mermaid rendering

We are creating mermaid graphs and placing them directly in the `adoc`.
Then we are applying `asciidoctor-diagram` supported by `asciidoctorj-diagram`
in Maven to create `html/svg` output.

For a smooth start into a new software the Maven Project should be self contained 
and build successful without external dependencies. 
This works fine for `[ditaa]` diagrams, since it is written in Java.

==== external

For `[mermaid]` diagrams an external converter is required 
and you can observe this in debug mode

    [INFO] asciidoctor: DEBUG: Finding 'mmdc' in attributes
    [INFO] asciidoctor: DEBUG: Finding 'mmdc' in environment
    [INFO] asciidoctor: DEBUG: Found '/usr/local/bin/mmdc' in environment

We don't want users to install `sudo` stuff in whatever system the software is build.
It simply doesn't make a good impression to distribute software 
that fails creating the documentation and requires system changes. 
Distributors can't predict each CD/CI environment 
in which the software will be composed.

For a self-contained environment the conversion could be achieved with 
https://github.com/asciidoctor/docker-asciidoctor[docker-asciidoctor].

If we do accept an external dependency to the internat at build time
we might as well use the https://kroki.io/[Kroki Diagram Server/Service]
as described in 
https://docs.asciidoctor.org/browser-extension/diagrams-extension-option[Use Kroki via the diagrams extension].

[quote, see https://kroki.io]
____
Kroki creates diagrams from textual descriptions! +
Kroki provides a unified API with support for BlockDiag (.. Mermaid ..). +
Kroki provides a unified API for all the diagram libraries. 
____

Let's use kroki for simplicity

    <diagram-server-type>kroki_io</diagram-server-type>
    <diagram-server-url>https://kroki.io</diagram-server-url>
      <kroki-server-url>https://kroki.io</kroki-server-url>

As kroki is a free service you might experince server problems in you build

    [INFO] --- asciidoctor-maven-plugin:3.1.1:process-asciidoc (generate-html-docs) @ bm-traccar ---
    [INFO] Converted /home/kbeigl/git/bm/bm-traccar/src/asciidoc/setup-tests.adoc
    [INFO] asciidoctor: ERROR: bm-traccar-arc.adoc: line 25: 
                        Failed to generate image: 400 "Bad Request"
                        
Simply try again another time and make sure images are present
before checking in the latest html set.

Now we have created a cyclic compilation of documents 
which does not interrupt the build, can override existing source files
and allows developers to type and free their minds.


==== internal

For a clean documentation all html pages and svg graphics are deleted 
and documentation is generated with a local kiko server.

===== kroki with docker

This can be setup in a combined docker setting of kroki with a 'Mermaid companion':

[source,xml]
----
  # Start Mermaid companion (with plenty of memory/shm)
  docker run -d --name kroki-mermaid --memory=2g --shm-size=1g \
    -p 8002:8002 yuzutech/kroki-mermaid

  # Start main Kroki and link it to the companion
  docker run -d --name kroki --memory=2g --shm-size=1g \
    --link kroki-mermaid:mermaid \
    -e KROKI_MERMAID_HOST=mermaid \
    -e KROKI_MERMAID_PORT=8002 \
    -p 8000:8000 \
    yuzutech/kroki:latest
----

`kroki-mermaid` contains a pre-installed Chromium binary that works 
without any sandbox, without download, without `/dev/..` issues.

and with the maven configuration

[source,xml]
----
   <diagram-server-url>http://localhost:8000</diagram-server-url>
     <kroki-server-url>http://localhost:8000</kroki-server-url>
----

Here is a simple test

    curl -X POST http://localhost:8000/mermaid/svg -d 'graph LR; A-->B'

to get a sample svg (text) as response.

If you only install the kroki server on ubuntu 
you can run into Puppeteer/Chromium problems.
This may not be a longterm solution 
as the images are pretty big chunks
(and not feasible for cd/ci)

[source,xml]
----
docker images
REPOSITORY               TAG             SIZE
traccar/traccar          6.10.0-ubuntu     313 MB
yuzutech/kroki           latest          2.41  GB
yuzutech/kroki-mermaid   latest          1.06  GB
----

and the docker command line is claiming a lot of memory.

The `mmdc` command line is probably much 'cheaper'...

===== Mermaid CLI `mmdc`

  mermaid diagrams require the Mermaid CLI (mmdc) to be installed
  (Node.js + @mermaid-js/mermaid-cli)
  so asciidoctorj-diagram can render to SVG.

  ensure mermaid CLI is installed on the build machine
  (Node + npm install -g @mermaid-js/mermaid-cli)

  install Mermaid CLI (mmdc) on the build machine
  (global npm install -g @mermaid-js/mermaid-cli)
  so asciidoctorj-diagram can call it.

  Ensure mermaid CLI (mmdc) is available on the build machine (needed to render mermaid to SVG):
  - install Node.js if missing
  - npm install -g @mermaid-js/mermaid-cli
  - ensure mmdc is on PATH

=== outlook

For the time being we can type into the adocs as we please. +
This is the top priority for a software creation process. +
At a later stage we might introduce a

    <module>bm-documentation<module> 

project at the end of the build.
This follows the idea of an aggregator module (standard Maven best practice for complex builds) 
that can pull previously zipped (`maven-assembly-plugin`) documents
from all projects, assemble them to one structure (`maven-dependency-plugin`)
and finally process them to a full site or single pdf etc.

As we learn to know AsciiDoc we add more features and head towards this finalization.
Hava a look at the `bm-parent.adoc` how to create a single page with toc 
and counter check the output `bm-parent.html` file .



















