
= Maven `<plugins>`

Each section provides a short introduction to each tool 
with links to lookup and learn more details.

== Asciidoctor 

The complete project is documented in _AsciiDoc_ or `.adoc` files.
This is the broader approach to technical documents than `markdown`
and you can find everything in the 
link:https://docs.asciidoctor.org/asciidoc/latest[AsciiDoc Language Documentation]:

[quote, see https://docs.asciidoctor.org/asciidoc/latest]
____
AsciiDoc is a lightweight and semantic markup language primarily designed for writing technical documentation. 
The language can be used to produce a variety of presentation-rich output formats, such as HTML, PDF, EPUB3, man(ual) page, or DocBook. 
This capability enables it to be used in static site generators, IDEs, git tools and services, CI/CD systems, and other software.
____

It is important to understand that `.adoc` files are source files 
that should be processed to some target format.
This processor is called the _Asciidoctor_ and described in the
link:https://docs.asciidoctor.org/asciidoctor/latest[AsciiDoctor Documentation]:

[quote, see https://docs.asciidoctor.org/asciidoctor/latest]
____
Asciidoctor is a fast text processor for parsing AsciiDoc into a document model, then converting it to output formats.
____

Goto projects 
xref:./ascii-doctor.adoc [AsciiDoctor implementation and usage]


== Mermaid Chart 

[quote, see https://docs.mermaidchart.com/mermaid-oss/intro/index.html#about-mermaid]
____
Mermaid lets you create diagrams and visualizations using text and code.
____

that's about all there is to say about this software.

Find more at https://github.com/mermaid-js/mermaid#readme[github]

The idea is to _describe_ charts with the mermaid syntax

[source,xml]
----
    flowchart TD
            A(["Start"])
            A --> B{"Decision"}
            B --> C["Option A"]
            B --> D["Option B"]
----

and our Maven Plugin combination of AsciiDoc and Mermaid 
will generate html pages with SVG graphics on the fly:

[mermaid]
....
flowchart TD
        A(["Start"])
        A --> B{"Decision"}
        B --> C["Option A"]
        B --> D["Option B"]
....

There is also a 
link:https://mermaid.live[live editor] for interactive chart creation.

The Maven Installation is part of the Maven AsciiDoc installation 
and details can be found in its description
xref:./ascii-doctor.adoc [AsciiDoctor implementation and usage].


== openapi-generator-maven

The complete Traccar REST API is defined in a single `openapi.yaml` file 
This file is used with the  
link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator] 
to generate a plain Java Client. 
The generation is controlled and configured via 
link:https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin[openapi-generator-maven-plugin] 
and produces a `traccar-api-generated-x.y.z.jar` (in two steps).

xref:../../../bm-traccar/traccar-openapitools-client/src/asciidoc/openapitools.adoc[details ...]


== Google Code Style

There are many code formatters and formats out there.
Just like in the `jeets` project we chose the   
https://github.com/spotify/fmt-maven-plugin[fmt-maven-plugin]

       <groupId>com.coveo</groupId>
    <artifactId>fmt-maven-plugin</artifactId>

The choice is based on simplicity and the most common code style with 
link:https://google.github.io/styleguide/javaguide.html[Google Java Style]. +
The plugin is strict about styling, cannot be configured by design 
and automatically formats the code before compilation.


== Testing with Traccar Server

The Traccar Clients are basically an interface between REST and Java passing Entities. 
Therefor there is no need for cumbersom JUnit test setups or mocking 
to test the technology we rely on.
The functionality is achieved by wiring diffent technology components
together, configure and run them.

The Traccar Client is _not_ a software with complex implementations of Java Units.
Actually it is merely an interface between REST and Java passing Entities. 
The functionality is achieved by wiring diffent technology components
together, configure and run them.

For example the Camel `RestOpenApiComponent` 
is already being tested with each Camel build. These tests should not be repeated. 
see 
https://github.com/apache/camel/tree/main/components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi[RestOpenApiComponent JUnit tests]

=== surefire vs failsafe testing with docker

The aim of this project is to remote control a Traccar Server 
by reacting to live information. +
So we can take a broader approach to testing by setting up a Traccar Server for tests.
This makes the actual build of the Traccar Client software faster.
We use the Maven lifecycle to start a traccar docker container 
and apply failsafe to _make sure the container is stoped after testing_:

    [INFO] --- docker-maven-plugin:0.46.0:stop (stop) @ traccar-api-client ---
    [INFO] DOCKER> [traccar/traccar:6.7.1-ubuntu] "traccar": 
                    Stop and removed container 7ef24f3a8f58 after 0 ms

To speed up test development the traccar container can be started via command line 
and the Integration Tests (**IT*) can be run as JUnit Tests against a running server.
This is a one liner _inside the `bm-traccar` branch_

[source,xml]
----
~/git/bm/bm-traccar$ mvn docker:run
[INFO] --- docker-maven-plugin:0.46.0:run (default-cli) @ bm-traccar ---
[INFO] DOCKER> [traccar/traccar:6.10.0-ubuntu] "traccar": Start container 6083b17b2da9
[INFO] DOCKER> [traccar/traccar:6.10.0-ubuntu] "traccar": Waiting on url http://localhost with method HEAD for status 200..399.
[INFO] DOCKER> [traccar/traccar:6.10.0-ubuntu] "traccar": Waited  on url http://localhost 4954 ms
----

The developer can login to the Traccar Frontend to inspect test results and more.

The botton line is that emphasis is placed on integration testing 
using Maven’s Failsafe plugin in combination with Docker. 


=== docker-maven

Requirements to docker are dead simple:
We need a traccar container out of the box, configure it to our needs, 
introspect the logs at runtime and finally using the traccar UI 
to visualize what's going on!

Since the project does not dockerize anything,
the plugin should not be to fancy about docker, kubernetes, cloud etc.
After setting up the project once, the focus is on using Spring Test framework 
and Camel's testing utilities to `mvn verify` integration logic and not unit-level.

There is no need to integrate Docker into the source code with
https://camel.apache.org/components/4.8.x/docker-component.html[Docker :: Apache Camel]
or the like, since this is not a docker project.
 
The choice is fabric8's `docker-maven-plugin` 
 
[quote,fabric8io/docker-maven-plugin] 
____
This is a Maven plugin for managing Docker images and containers. +
It focuses on two major aspects for a Docker build integration: +
Building Images and  Running Containers.
____


=== maven-failsafe
 
specifically for integration testing, focusing on lifecycle and reporting for integration tests.

Run Docker containers during the integration test phase to manage container lifecycle.

Failsafe and Docker Integration: Combining Failsafe plugin with Docker management 
to execute tests within a Dockerized environment and ensure proper test lifecycle.

https://maven.apache.org/surefire/maven-failsafe-plugin/ +
https://maven.apache.org/surefire/maven-failsafe-plugin/usage.html

  -> Usage in multi-module projects
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>

  -> Reporting integration test results   LATER
    <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-report-plugin</artifactId>


== flatten-maven


