
= Maven Wrapper

To make sure that the complete project is build with a specified Maven Version
it is possible to add a Maven Wrapper with a determined version.

Simply run this from the root directory

    ~/git/bm$ mvn wrapper:wrapper -Dmaven=3.8.8

to get

    bm/
    ├── .mvn/
    │   └── wrapper/
    │       ├── maven-wrapper.jar
    │       └── maven-wrapper.properties
    ├── mvnw
    ├── mvnw.cmd
    ├── pom.xml (Root POM)
    ├── bm-parent/
    │   └── pom.xml
    └── etc.
    
Now we can build the complete multimodule project from the root with

    /git/bm$ ./mvnw clean install

And you can build any subproject _from the root_ with 
    
    /git/bm$ ./mvnw clean install -pl bm-tracker    -am
    /git/bm$ ./mvnw clean install -pl bm:bm-tracker -am
    
Or, better, if you are working inside a subproject like the `gps-osmand-tracker`
    
      ~/git/bm/bm-tracker/gps-osmand-tracker$ ../../mvnw clean install
      
Note that you reference the `mvnw` in the root by going up two folders
with `../../` + 
depending on where you are working from the command line.

Since this setup is generally idempotent the wrapper can be upgraded
anytime with

        ~/git/bm$ mvn wrapper:wrapper -Dmaven=3.9.2
    
Then the next build will pick up the required files.

    
= Maven maintenance & release


== upgrades and updates

After releasing a repository version `v1,0`, `v1.1.1-SNAPSHOT` or `-RC` etc. 
the major versions are upgraded. +
The following steps cover the vital coordinates. 

=== step 1 - maven versions  

  mvn versions:display-plugin-updates

=== step 2 - Camel and Spring versions  

The above maven command does not check the BOM versions.
Therefor they are incremented one by one until the repository
is completly build with `mvn install`.

        <camel-version>4.10.6</camel-version>
  <spring-boot-version>3.4.7</spring-boot-version>

We usually stick to the `LTS` versions provided.

=== step 3 - Java and JDK versions

Upgrading Java can be fine for the repository.
Nevertheless we would like to keep a compromise between highest available 
and lowest backward compatibility for users of the released jar files.

        <jdk.version>21</jdk.version>

=== step 4 - Traccar versions

This step is more than just a change of pom coordinates.
Traccar always has and still is evolving at a high pace and
for this repository especially the REST API is vital.
Therefor we go through this upgrade process, if there is time :(

For your purposes check the API version and most REST calls 
have been available for years and should be (backward) compatible
to your Traccar Server Version.

And the

    org.openapitools:openapi-generator-maven-plugin .. 7.13.0 -> 7.14.0

should be updated with the Traccar Version.

 
=== useful mvn commands

Maven also provides 

    dependency:analyze 
    
plugin goal for analyzing the dependencies:
it helps making this best practice more achievable.

Most Maven plugins have a help goal
that prints a description of the plugin and its parameters and types. +
For instance, to see help for the javadoc goal, type:

      mvn javadoc:help -Ddetail -Dgoal=javadoc

 