
= Database Testing

[toc]

Multiple options for handling the H2 database are described, 
including mounting external volumes, direct SQL shell access, 
and automation scripts for admin user setup. +
The documentation describes different database introspection approaches 
for development and testing.

options

    create external volume for h2 database
       delete to create new one
       admin/admin hen and egg problem
       create admin/admin for template
       apply web.serviceAccountToken on truncated db
       
    run traccar with brand new internal h2
       check durations during/between tests
       
    do not access database as backdoor: Entities vs DTOs
    
    work with Traccar Frontend with running docker
    
    
The [DatabaseTest] setup we will look at different options to develop 
with database introspection ...

You can always inspect `h2` through its console,
as a back door directly the database model. + 
The default h2 database is ideal, i.e. made for testing.
Developers can login to the traccar data base, explore the schema 
and inspect data with `plain SQL`, reset to scratch .. whatever.

=== database introspection

The recommended traccar docker installation is to leave the database inside the container.
By mounting the `/data` folder we can look inside the data, which stays persistent
after the container has stopped. + 
Note that the H2 database is locked as long the traccar container is working. + 
Find database management and manipulation 
link:../databaseTest.adoc[here] .



== automate admin/admin
 
insert initial admin user in Dockerfile

gemini: + 
API: While Traccar has a REST API, using it for initial user setup 
might be tricky since the API itself requires authentication. 
Directly database manipulation or configuration file manipulation 
is more reliable for initial setup.

problem: schema is only created with first start of traccar-server.jar

    root@d3b6ba0d8261:~# pwd
    /root
    root@d3b6ba0d8261:~# java -cp /opt/traccar/lib/h2-2.3.232.jar org.h2.tools.Shell 
                              -url jdbc:h2:/opt/traccar/data/database 
                              -user sa
    
    Welcome to H2 Shell 2.3.232 (2024-08-11)
    Exit with Ctrl+C
    
    sql> select * from tc_users
    ...> ;
    Error: org.h2.jdbc.JdbcSQLSyntaxErrorException: 
           Table "TC_USERS" not found (this database is empty);

possible solution: add schema/createadmin.xml if admin doesn't exist


== sql shell

https://www.baeldung.com/java-h2-db-execute-sql-file
    
    java -cp /path/to/h2/jar/h2-version.jar org.h2.tools.RunScript
         -url jdbc:h2:db/server/url
         -user sa -password password
         -script script.sql
         -showResults


  java -cp /opt/traccar/lib/h2-2.3.232.jar org.h2.tools.Shell 
       -url jdbc:h2:/opt/traccar/data/database 
       -user sa
       
=== install in traccar/h2/

  $ java -cp /opt/traccar/h2/bin/h2-2.3.232.jar org.h2.tools.Shell 
         -url jdbc:h2:/opt/traccar/data/database 
         -user sa

  sql> select * from tc_users;
  ID | NAME | EMAIL | HASHEDPASSWORD | SALT | READONLY | ADMINISTRATOR | MAP | LATITUDE | LONGITUDE | ZOOM |
  ATTRIBUTES | COORDINATEFORMAT | DISABLED | EXPIRATIONTIME | DEVICELIMIT | USERLIMIT | DEVICEREADONLY |
  PHONE | LIMITCOMMANDS | LOGIN | POILAYER | DISABLEREPORTS | FIXEDEMAIL | TOTPKEY | TEMPORARY
  (0 rows, 1 ms)

  select NAME, EMAIL, HASHEDPASSWORD, SALT, READONLY, ADMINISTRATOR 
    from tc_users;
  (0 rows, 1 ms)

=> empty database schema in place

== database available / locked

  docker:run

  $ java -cp /opt/traccar/h2/bin/h2-2.3.232.jar org.h2.tools.Shell -url jdbc:h2:/opt/traccar/data/database -user sa
  Exception in thread "main" org.h2.jdbc.JdbcSQLNonTransientConnectionException:
    Database may be already in use: "/opt/traccar/data/database.mv.db".
    Possible solutions: close all other connection(s); use the server mode [90020-232]
  Caused by: org.h2.mvstore.MVStoreException:
    The file is locked: /opt/traccar/data/database.mv.db [2.3.232/7]

     localhost/register -> admin/admin admin@domain.org

     stop container

    sql> select NAME, EMAIL, HASHEDPASSWORD, SALT, READONLY, ADMINISTRATOR from tc_users;
    NAME             | EMAIL | HASHEDPASSWORD                                   | SALT                                             |
    admin@domain.com | admin | 3411c354bc1661db4f1e358331a6a4394e6fd1c96bc1cc30 | d4d204fce88c333de097786fd9636a656c25bc1e4ea9b5ca |

    READONLY | ADMINISTRATOR
    FALSE    | TRUE
    (1 row, 20 ms)

    docker run -> user is available -> hash & salt vary !!

    | HASHEDPASSWORD                                   | SALT
    | 3411c354bc1661db4f1e358331a6a4394e6fd1c96bc1cc30 | d4d204fce88c333de097786fd9636a656c25bc1e4ea9b5ca
    | 42d4bf701495e2105dddfd66e3989919c218a6d7b99c623d | d3e47507a6fdcc624b8bd3bc85ce96bab195c335b76044a6


let's see:

    sql> delete from tc_users;
    Error: org.h2.jdbc.JdbcSQLNonTransientException:
    The database is read only; SQL statement: delete from tc_users [90097-232]

    -> change access to database* files
    $ sudo chmod 777 database*
    => works :)

    prepare statement to createAdminUser.sql
    INSERT INTO tc_users (name, email, hashedpassword, salt, administrator) 
    VALUES ('admin', 'admin@domain.com', '3411c354bc1661db4f1e358331a6a4394e6fd1c96bc1cc30', 'd4d204fce88c333de097786fd9636a656c25bc1e4ea9b5ca', true);

    sql> INSERT INTO tc_users (name, email, hashedpassword, salt, administrator)
    VALUES ('admin', 'admin@domain.com', '3411c354bc1661db4f1e358331a6a4394e6fd1c96bc1cc30', 'd4d204fce88c333de097786fd9636a656c25bc1e4ea9b5ca', true);
    (Update count: 1, 5 ms)
    
    sql> select * from tc_users;
    ID | NAME  | EMAIL            | HASHEDPASSWORD | SALT                                                                               | READONLY | ADMINISTRATOR
    2  | admin | admin@domain.com | 3411c354bc1661db4f1e358331a6a4394e6fd1c96bc1cc30 | d4d204fce88c333de097786fd9636a656c25bc1e4ea9b5ca | FALSE    | TRUE

Note ID++ in new db! -> only apply ids after semantic lookup !

    -> mvn docker run
       localhost/login appears :)
       login: email: admin@domain.com pw:admind

    I want login name/pw ..
    delete database* files
    mvn docker:run creates new database* files with empty schema

    statement to createAdminUser.sql without email !!
    NULL not allowed for column "EMAIL";

    -> insert above again
       mvn docker run
       localhost/login appears :)
       login: email: admin@domain.com pw:admind

    sql> select * from tc_users;
        ID | NAME  | EMAIL
        2  | admin | admin@domain.com

== hashing the password

https://www.traccar.org/forums/topic/hashing-the-password/

    # generate a random salt
    salt="$(dd if=/dev/urandom bs=24 count=1 status=none | xxd -p)"
    
    # generate the password hash from the contents of the "password" variable (which you've to set yourself to the new cleartext password)
    hash="$(openssl-3.0.1 kdf -keylen 24 -binary -kdfopt digest:sha1 -kdfopt "pass:$password" -kdfopt "hexsalt:$salt" -kdfopt iter:1000 pbkdf2 | xxd -p)"
    
    # uncomment the following line to print out both the salt and the password hash (if you want to)
    #echo -e "salt: $salt\nhash: $hash"
    
    # set the value of "tchome" to the path of the Traccar directory
    tchome="/opt/traccar"
    
    # and finally update the password (and salt) of the default "admin" user
    java -cp "$tchome/lib/h2-"*".jar" org.h2.tools.Shell -url "jdbc:h2:$tchome/data/database" -user sa -sql "update tc_users set hashedpassword='$hash', salt='$salt' where email = 'admin';"



== sql with Maven

    https://github.com/kbeigl/jeets/blob/master/jeets-models/pom.xml

            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2database-version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.dbunit</groupId>
                <artifactId>dbunit</artifactId>
                <version>${dbunit-version}</version>
                <scope>test</scope>
            </dependency>

