
= repository documentation

The repository is documented in all layers of aggregate and regular modules.
Documentation is written with `.adoc` files to use many of its features,
basically from crosslinks to more complex things like integrating charts.
You should be aware that `.adoc` files are actually source files
to be compiled with `AsciiDoc` to a variety of presentation-rich output 
formats, like a complete website or pdf.

[TIP]
====
At development time you should browse the `.adoc` files to edit, +
while the `.html` files are produced for releases. +
During development you can ignore the `.html` files in your commits. 
====


== what do you see now?

You are now looking at the main `readme.adoc` of this repository.

If you are viewing the file through `github` then the site 
is rendering the links below and you can follow one of them.

If you are looking at the same file on your local filesystem
through a browser the links must not work, because it requires
a preview extension to create them from `ascii` format.
Then again you will not see the integrated charts in the documents
as they also require a separate extension or online tool.

== choose your format

We are using the `asciidoctor-maven-plugin` to convert 
every `.adoc` file to a `.html` page, which does not require 
any settings on your browser or elsewhere.

The following links point to the repository parent `bm.adoc` or `bm.html`. +
Choose your own entry point and format to navigate through the documentation.

bm repository documentation entry points: 
link:./src/asciidoc/bm.adoc[adoc] or
link:./src/asciidoc/bm.html[html] format

