:toc: left


= Quickstart: Real Time Console

The three layers around the `ApiClient`, `Api interface` and `RealTimeManager` +
are combined in the `@SpringBootApplication  RealTimeClient`.

== todo: merge into doc

The `traccar-rt-client` implies the other artifacts of the `/bm-traccar` branch 
as required layers and can well serve as a Quickstart 
(and later as a useful supporting component) for Traccar Client development.
Also the `traccar-realtime-client` is a Spring Boot application, 
which means that it can be run as a standalone application.

The real time client can easily be integrated into your Spring Boot applications.
You can use the `RealTimeManager` as a bean in your application context and
add a little ETL logic to process the Traccar Entities as you like.

Please check the
xref:./bm-traccar/traccar-realtime-client/traccar-realtime-client-qs.adoc[Quickstart]
to get started with the `traccar-realtime-client` and 
find out how it can be used to connect to a Traccar server and 
receive real-time data from it.

== `traccar-rt-client` *Release*

The `traccar-rt-client` is a simple client application that connects 
to a traccar server and listens for real-time updates. 
It can be used as a solid building block for real time applications.
You can integrate it in your application and code against the
`RealTimeManager` as if it was the traccar server.

We will go through the steps for the simplest case, +
havng _one_ user without special permissions +
with _one_ device on the server.

[TIP]
====
Logon to the traccar server to witness the motion of your devices on the map +
and open the console to see the real time updates as they come in.
====

=== download release

pick a version of the `traccar-realtime-client-u.v.w-x.y.z[-suffix].jar`.

The first Release Candidate is `traccar-realtime-client-6.12.2-1.1.20-RC.jar`

Download the jar in any folder

    /any/folder/traccar-realtime-client-6.12.2-1.1.20-RC.jar
    
It was `repackaged` with the `spring-boot-maven-plugin` +
to include Spring Boot dependencies and the `application.properties` file. +


=== console output

login process and loading of initial data from the server

[source,xml]
----
    Login RealTimeController for 'kbeigl@web.de' to traccar server 'https://demo3.traccar.org` ...
    --- Loading initial users from server...   ---
    --- Loading initial devices from server... ---
    Device.id879: Kristof
    Connected to WebSocket on demo3.traccar.org:443
    User logged in: Kristof
    RealTimeController started and logged in successfully.
    Application running. Press Ctrl+C to exit.
----
    
[NOTE]
====
As desccribed above we are demonstrating the simplest case with one user, 
restricted permissions and a single device. 
You can see that this user does not have access to any users,
but the device `Device.id879` is loaded and available in the client.
This is the device we are tracking.
====

and finally the real time updates as they come in

[source,xml]
----
    positions message received: {positions=[{id=74626756, attributes={..}, deviceId=879 ...
    PositionProcessor: received 1 Position message/s.
    process json message: [{id=74626756, attributes={..}, deviceId=879 ...
                                                          ============
----

until you shutdown the connection:

[source,xml]
----
    : Graceful shutdown initiated.
    Apache Camel 4.18.0 (camel-1) is shutting down (timeout:45s)
    Routes stopped (total:3)
        Stopped traccar-ws-dynamic-route (vertx-websocket://wss://demo3.traccar.org/api/socket)
        Stopped process-websocket-message-route (direct://start-websocket-connection)
        Stopped traccar-login-route (direct://traccarLogin)
    Apache Camel 4.18.0 (camel-1) shutdown in 24ms (uptime:58s)
----

Happy Tracking :)