
:toc: 

= Quickstart: Real Time Console

The three layers around the `ApiClient`, `Api interface` and `RealTimeManager` +
are combined in the `@SpringBootApplication  RealTimeClient`.

== `traccar-rt-client` *Release*

The `traccar-rt-client` is a simple client application that connects to a traccar server and listens for real-time updates. 
It can be used as a solid building block for real time applications.
You can integrate it in your application and code against the
`RealTimeManager` as if it was the traccar server.

We will go through the steps for the simplest case, +
havng _one_ user without special permissions +
with _one_ device on the server.

[TIP]
====
Logon to the traccar server to witness the motion of your devices on the map +
and open the console to see the real time updates as they come in.
====

=== prerequisites

All you need is 

* a Java runtime and online access to the Traccar Server
* a *Traccar Server Address* to connect to and a *User Account*
* a *Device* on a traccar server to connect to.

[TIP]
====
If you are not familiar with traccar server, you can sign up on a public demo server +
and use your smartphone as a tracker with the traccar client app ... within minutes!
====


=== download release

You can pick up the latest release from the 
https://github.com/kbeigl/bm[repo home],
go the Release section and click on *latest* label.

Or look at all 
https://github.com/kbeigl/bm/releases[realeases] 
and pick a version of the `traccar-realtime-client-u.v.w-x.y.z[-suffix].jar`.

The first Release Candidate is `traccar-realtime-client-6.12.2-1.1.20-RC.jar`

Download the jar in any folder

    /any/folder/traccar-realtime-client-6.12.2-1.1.20-RC.jar
    
Note that the 

    traccar-realtime-client-u.v.w-x.y.z[-suffix].jar.original
                                                    ---------
                                                    
is the original jar without the `application.properties` file. +
It was `repackaged` with the `spring-boot-maven-plugin` +
to include Spring Boot dependencies and the `application.properties` file. +


=== provide credentials 

Extract the `application.properties` from the jar and copy it to the same folder as the jar:

    $ cd /any/folder
    $ jar xf traccar-rt-client-6.10.0-RC.jar application.properties

Or create a new `application.properties` file in the same folder +
and provide the necessary credentials and server address. +
For example:

[source,xml]
----
    # http:// or secure https://
    traccar.protocol=https://
    
    # port can be empty for default port (80 for http, 443 for https)
    traccar.port=

    traccar.host=${traccar.protocol}demo3.traccar.org${traccar.port}
    
    traccar.name=acount name
    traccar.password=secret
    traccar.email=my@mail.com
----


=== prepare tracking

Login to the traccar server with the provided credentials and make sure you have a device on the server. +
Turn on the tracker and make sure it is connected to the server, sending updates and showing up on the map.

=== run the client

First make the jar executable:

    $ chmod 777 traccar-realtime-client-6.12.2-1.1.20-RC.jar
    
Then execute the jar:

    $ java -jar traccar-realtime-client-6.12.2-1.1.20-RC.jar

Note that the client remains running until manually shutdown gracefully with `Ctrl+C`.

=== console output

First you will see the startup messages

[source,xml]
----
    Starting RealTimeClient using Java 21.0.10 with PID 704815
    Apache Camel 4.18.0 (camel-1) is starting
    Routes startup (total:2)
    Started RealTimeClient in 3.519 seconds (process running for 4.207)
----

then the login process and loading of initial data from the server


[source,xml]
----
    Login RealTimeController for 'kbeigl@web.de' to traccar server 'https://demo3.traccar.org` ...
    --- Loading initial users from server...   ---
    --- Loading initial devices from server... ---
    Device.id879: Kristof
    Connected to WebSocket on demo3.traccar.org:443
    User logged in: Kristof
    RealTimeController started and logged in successfully.
    Application running. Press Ctrl+C to exit.
----
    
[NOTE]
====
As desccribed above we are demonstrating the simplest case with one user, 
restricted permissions and a single device. 
You can see that this user does not have access to any users,
but the device `Device.id879` is loaded and available in the client.
This is the device we are tracking.
====

and finally the real time updates as they come in

[source,xml]
----
    positions message received: {positions=[{id=74626756, attributes={..}, deviceId=879 ...
    PositionProcessor: received 1 Position message/s.
    process json message: [{id=74626756, attributes={..}, deviceId=879 ...
                                                          ============
----

until you shutdown the connection:

[source,xml]
----
    : Graceful shutdown initiated.
    Apache Camel 4.18.0 (camel-1) is shutting down (timeout:45s)
    Routes stopped (total:3)
        Stopped traccar-ws-dynamic-route (vertx-websocket://wss://demo3.traccar.org/api/socket)
        Stopped process-websocket-message-route (direct://start-websocket-connection)
        Stopped traccar-login-route (direct://traccarLogin)
    Apache Camel 4.18.0 (camel-1) shutdown in 24ms (uptime:58s)
----

Happy Tracking :)



