
= The OsmAnd GPS Tracker

The `gps-osmand-tracker` is a Java Client Software to simulate 
a standard device that _collects_ GPS locations, optionally buffer 
and send them to a server asap.
Reporting should be configurable for time- and distance intervals,
change of direction etc.


== Tracker Components

[NOTE]
====
Note that we are citing original texts from  
link:https://www.amazon.com/GPS-Tracking-Java-Components-Challenges/dp/1138054941[GPS Tracking with Java EE Components]
====


[quote,GPS Tracking with Java EE Components, Chapter 8.1]   
What exactly is a tracking device and what is its core functionality? +
A tracker hardware is basically a combination of a GPS (processing) unit
and a (GSM) communication unit. The GPS receives the location via satellite and
the communication unit sends tracking messages to a server. +
&#8230; +
 In the end every
tracker should be able to send Coordinates, preferably WGS84 latitude and
longitude and universal time, which the Server can use to localize the device.

The main components are the GPS receiver and GSM transmitter chips
for receiving and sending locations.
Since both chips have to deal with a lot of information and technical challenges
they can not really be synchronized.
Therefor a third component is important: 
A Message Buffer serves as a local database to keep the best location results
and wait for a good connection to transmit them to the Tracking System.

The fourth component, the Energy Source is vital for the hardware Tracker
but is not needed for the software simulation.
A simple `batteryLevel` attribute is enough to keep track.


=== OsmAnd Protocol

We chose this protocol because it is very simple and it is implemented
on the Traccar Server for the Traccar Client App.
You can find the format (or protocol spec) 
link:https://www.traccar.org/osmand/[here] and
xref:OsmAndProtocolSpecification.adoc[here].

Technically "The OsmAnd protocol processes HTTP requests 
with either query parameters or POST parameters."

As we are initially interested to transmit place & time 
we can focus on the following parameters that _could be used_
in a simple record (immutable data class) to hold 
a single GPS location: 

[source,java]
----
    public record GpsData(
        double  latitude,
        double longitude,
        double  altitude,
          long timestamp,
        double speed,
        double bearing,
           int battery) {}
----

[quote, https://docs.oracle.com/en/java/javase/17/language/records.html, Record Classes]
Record classes, which are a special kind of class, help to model plain data aggregates + 
with less ceremony than normal classes.

Another approach would be to generate a Java Class from 
the JSON format listed on the 
link:https://www.traccar.org/osmand/[same page]. 


=== GPS receiver

A GPS chip receives signals from orbiting satellites to calculate
the location on Earth - a highly mathematical, trigonomic number cruncher.
The location is continuously calculated by trilateration from three satelites. 
Note that a fourth satelite is required to provide the precise time.

It is useful to understand that a GPS unit is primarily concerned
to deliver `latitude, longitude` and `time`. 
The `altitude` is more of a side effect and not as reliable.

This implies that the GPS unit primarily provides point information.
`speed` and `bearing` _can be_ provided, but most Tracking Systems
calculate them from the previous to the current positon.


=== GSM transmitter

The GSM is basically the entry point to the internet. 
It can send the locations over the connected network (if available) 
and can communicate via TCP and UDP low level protocols.
This unit is also working all the time to get a good connection
over the air and transmitting whenever possible.


=== Message Buffer

As both GPS- and GSM units are busy all the time
the Message Buffer can collect all valid and accurate locations
from the GPS, while pushing them to the server via GSM.


