
= Implementation

We have started be defining the OsmAnd GPS Message as defined for Traccar.
That is the information and format the server accepts and understands.
We will use it as our Model for development.



xxxxxxxxxxx

We'll start with a simple class definition for the Tracker Simulation

[source,java]
----
    public class GpsOsmTracker {
    
      private final String serverUrl;
      private final String deviceId;
    
      // JTS Coordinate to hold (lon, lat, alt) -> (x, y, z) mutable states
      private final Coordinate coordinate;
    
      // Other telemetry data (not part of geometry)
      private long timestamp;
      private double speed; // in meters/second
      private double bearing; // in degrees (0-360)
      private int batteryLevel; // 0-100
      private double hdop; // Horizontal Dilution of Precision, i.e. accuracy
----

This way the GPS unit is replaced by simply setting the GPS class members.
So we can add getters and setters for each member.

=== Geo Coordinates

Note that we are using the `org.locationtech.jts.geom.Coordinate` 
to store the `latitude, longitude` and `altitude` double values.
This is our entry point to geographical libraries for GPS Positions,
for dealing with Digital Maps and Geographic Information Systems.

We can replace the simple double fields for the location 
with a core class from the GeoTools / JTS (Java Topology Suite) library, 
which is the standard geometry model GeoTools is built on.

At this point it doesn't seam like a big deal, 
because we simply storing three double values in one Coordinate.
But as soon as we need to calculate `distance` and `bearing`
we have to use a projection system.
This is a walk in the park with 
the GeoTools library's built-in `GeodeticCalculator`.

==== Example

To calculate the geodesic distance in meters between two lat/lon points 
using the GeoTools GeodeticCalculator 
with the GPS standard WGS84 (EPSG:4326) system: 

<1> Define the Coordinate Reference System 

<2> Initialize the Geodetic Calculator

<3> Set start- and end coordinates 

<4> Get the orthodromic distance (distance along the ellipsoid surface)

[source,java]
----
  CoordinateReferenceSystem wgs84 = CRS.decode("EPSG:4326");     // <1>

  GeodeticCalculator calculator = new GeodeticCalculator(wgs84); // <2>

  calculator.setStartingGeographicPoint   (lon1, lat1);          // <3>
  calculator.setDestinationGeographicPoint(lon2, lat2);

  return calculator.getOrthodromicDistance();                    // <4>
----

