
= Dockerized Traccar Server

The Traccar Client Software is developed with Integration Tests against a Docker Traccar Server.

== build and run Traccar Docker Container

The traccar project at Github provides instructions to fetch and install the Traccar
https://hub.docker.com/r/traccar/traccar[DockerHub image].
This Maven Module leverages the
https://github.com/fabric8io/docker-maven-plugin/blob/master/README.md[`fabric8io docker-maven-plugin`] 
to control the Docker container phases to manage a dockerized Traccar server 
for integration testing. 

To avoid the `sudo` command you can create a docker group to enable non-root user access:

[source,text]
-----------------
    sudo groupadd -f docker
    sudo usermod -aG docker $USER
    newgrp docker
    groups
-----------------

== `docker-maven-plugin`

You can compare the parameters of the `docker-maven-plugin` 
with the four point checklist at
https://hub.docker.com/r/traccar/traccar#container-create-example[Container create example]
and adopt them to your requirements and system.

=== `<build>`

In the plugin `<configuration>` of the `<image>` and `<build>` section
you can find the traccar version and target OS.
Please note that this repository was set up with `Dockerfile.ubuntu`. 

[source,xml]
----
    <traccar.version>6.8.0</traccar.version>
    <docker.image.version>${traccar.version}</docker.image.version>
    <docker.image.os>ubuntu</docker.image.os>
----

You might want to swap with `Dockerfile.alpine` or `Dockerfile.debian`
for your purposes.

[source,xml]
----
    <artifactId>docker-maven-plugin</artifactId>
     ...
    <image>
        <alias>traccar</alias>
        <name>traccar/traccar:${traccar.version}-${docker.image.os}</name>
----

creates an image `traccar/traccar:6.8.0-ubuntu` 
just like the command line

    $ docker pull traccar/traccar:6.8.0-ubuntu

Note that we distinguish `project-` and `${traccar.version}` 
in order patch versions, when required.


==== `<dockerFile>` 

The Dockerfile is not part of this project and is directly referenced with its `${traccar.version}` 
from the sources at github 
[source,xml]
----
    <dockerFile>Dockerfile.${docker.image.os}</dockerFile>
    <contextDir>https://github.com/traccar/traccar/blob/v${traccar.version}/docker</contextDir>
----

The docker file ...

    - defines os version image, ie ubuntu:24:04
    - grabs the https://github.com/traccar/traccar/releases[traccar release] 
      from github and unzips
    - provides entry point, ie java cmdline
    - *expects a* `WORKDIR /opt/traccar` *on your machine!* +
      which we will provide next.
   
== `docker:run`

Now we are almost ready create a container from the image and run it. + 
Back to the traccar instructions we are asked to create workdirectories
and `chmod` as you like.

=== create work directories

&#8230; and set permissions according to your policies.

  sudo mkdir -p /opt/traccar/
  sudo chmod 777 traccar

=== cat default traccar.xml

*cat* the `traccar.xml` file to your local file system. +
Make sure you pick the correct name, version and flavor for `traccar/traccar:6.6-ubuntu` . +
_This time we are directly applying_ the `docker run` command without `mvn` !

    $ docker run --rm --entrypoint cat traccar/traccar:x.y.z-ubuntu \
       /opt/traccar/conf/traccar.xml > /opt/traccar/traccar.xml

Now you should find the `traccar.xml` file as specified.
As an experienced traccar admin you can now configure traccar 
according to your production server.
Keep in mind that _this project_ does not require Tracker information 
nor opening the ports as described in `<port>` below. 

The focus _of this project_ is on interacting with the 
link:https://www.traccar.org/api-reference[Traccar API]
in the Traccar container.

=== create container

The last step creating the traccar container on the traccar Github page 
is to run direcly with docker `docker run`.
We do not want to run docker via command line,
we want to start and stop the container for integration testing.
So we will use `mvn docker:run` to make sure everything is in place.

=== `<run>`

Next you should check the parameters of the `<run>` section for your personal preferences

[source,xml]
----
        <run>
            <hostname>traccar</hostname>
            <ports>
                <port>80:8082</port>
            </ports>
            <volumes>
                <bind>
                    <volume>/opt/traccar/logs:/opt/traccar/logs:rw</volume>
                    <volume>/opt/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro</volume>
                    <volume>/opt/traccar/data:/opt/traccar/data:rw</volume>
                </bind>
            </volumes>
            <log><!-- do not remove --></log>
            <wait>
                <http>
                    <url>http://localhost</url>
                </http>
            </wait>
        </run>
----

==== `<port>`

Set the external port to 80 simplify the http url of the traccar UI to `http://localhost`.

[NOTE]
====
Please note that this project is for OpenAPI development and the access is restricted
to the port (default 80) of the UI. + 
The Tracker Protocol TCP and UDP Ports 

    --publish 5000-5150:5000-5150 \
    --publish 5000-5150:5000-5150/udp \
    
are not required _nor configured_ for API testing _in this project_. 
====

[TIP]
====
In order to test your Traccar Server in Docker with an Android or iPhone Traccar Client 
you can open the relevant port with

    <ports>
        <port>80:8082</port>
        <port>5055:5055</port>
    </ports>
====


==== `<wait>`

Wait for availabity of the container, before running tests.

[TIP]
====
Once the container has started you can also access the traccar UI 
in you local browser with `http://localhost` .
====

==== `<volumes>`

The volumes define the mapped traccar folders on your local system.

 . we want to `tail` the logfile to see what's going on on server side.
 . we want to configure the `traccar.xml` analog to the production server.
 . we want to see what's going on in the database.

These volumes represent the standard installation of traccar 
and `<traccar/data>` was added for development support. 

==== `<traccar/data>`

In the `<volumes>` section above you will find an additional volume

    <volume>/opt/traccar/data:/opt/traccar/data:rw</volume>

[TIP]
====
This way developers can always peak into traccar's data model. +
Different options to work with the Database are explained 
link:./databaseTest.adoc[here]
====

Also note the `Database` heading at the bottom of

    https://hub.docker.com/r/traccar/traccar

____
The default when executing the above docker run command is an internal H2 database.
 The docker run command also doesn't create a mount point on the host for the data folder
 which will cause the database to be lost when the container is recreated.
 This point can be mitigated by adding the line 
 
    -v /var/docker/traccar/data:/opt/traccar/data:rw \

____

==== `<log>`

Note that the empty 

    `<log><!-- do not remove --></log>` 

section _is required_ as described in
https://dmp.fabric8.io/#start-logging[5.2.10. Logging]:
____
Logging is enabled by default if a `<log>` section is given!
____

This way you can always keep a console or editor open 
to auto reload, i.e. `tail` the `tracker-server.log` file.


=== `mvn docker:run` 

Now we can execute: `mvn docker:run` and container start, wait, 
stop and remove should look something like this:

[source,text]
-----------------
~/git/bm/bm-traccar/traccar-api-camel$ mvn docker:run
                                       ==============
[INFO] --- docker-maven-plugin:0.46.0:run (default-cli) @ traccar-api-camel ---
[INFO] DOCKER> Pulling from traccar/traccar
 b08e2ff4391e: Pull complete 
 0b823ac9e80a: Pull complete 
 66fe9131b572: Pull complete 
 4f4fb700ef54: Pull complete 
[INFO] DOCKER> Digest: sha256:5bd7e3a8d059b1ca0e86004f747f6bebe9206f5b2da61b380f70c2a6285e59f5
[INFO] DOCKER> Status: Downloaded newer image for traccar/traccar:6.8.0-ubuntu
[INFO] DOCKER> Pulled traccar/traccar:6.8.0-ubuntu in 49 seconds 
[INFO] DOCKER> [traccar/traccar:6.8.0-ubuntu] "traccar": Start container 7ad9a7c7a649
[INFO] DOCKER> [traccar/traccar:6.8.0-ubuntu] "traccar": 
               Waiting on url http://localhost with method HEAD for status 200..399.
[INFO] DOCKER> [traccar/traccar:6.8.0-ubuntu] "traccar": Waited on url http://localhost 5900 ms
-----------------

Looks good: Container started and waited five seconds for the localhost.
We have manually started `mvn docker:run`, now we can manually stop the container 
with the familiar key combination `<Ctrl><c>` :

[source,text]
-----------------
^C
[INFO] DOCKER> [traccar/traccar:6.8.0-ubuntu] "traccar": 
               Stop and removed container 7ad9a7c7a649 after 0 ms
-----------------

_Now_ you can check your local system with docker command:

[source,text]
-----------------
~/git/bm/bm-traccar/traccar-api-camel$ docker images -a
                                       ================
REPOSITORY        TAG            IMAGE ID       CREATED       SIZE
traccar/traccar   6.8.0-ubuntu   5fdf770fa10b   6 weeks ago   298MB
-----------------


== validate development environment

Let's check, if everything is in place.

=== Traccar Frontend

If you run `mvn docker:run` again (and over and over) the docker pull should not show
as long as the docker image is on your machine. 
After waiting for startup (5.69 seconds in this case) &#8230; 

[source,text]
-----------------
[INFO] --- docker-maven-plugin:0.46.0:run (default-cli) @ traccar-api-camel ---
[INFO] DOCKER> [traccar/traccar:6.8.0-ubuntu] "traccar": Start container 6b39263a1f9c
[INFO] DOCKER> [traccar/traccar:6.8.0-ubuntu] "traccar": 
               Waiting on url http://localhost with method HEAD for status 200..399.
[INFO] DOCKER> [traccar/traccar:6.8.0-ubuntu] "traccar": Waited on url http://localhost 5690 ms
-----------------

&#8230; you can open the url in your browser.

[TIP]
====
At the development time you can open a console, execute `mvn docker:run` and leave it open.
This way you can execute Integration Tests (*IT) as Unit Tests against the Traccar Server in your IDE!
As good practice each test should clean up the server for subsequent tests in random order.

As an example you can debug a JUnit Test in your IDE, set a debug point after creating a new user
and then log _as this user_ in on the Frontend. Then continue the test to clean up.

Much more complex scenarios can be observed step by step in details.
====


=== `tracker-server.log`

In your local folder you should find the logfile

    /opt/traccar/logs/tracker-server.log

There you should see the server start and the database setup by liquibase. + 


[source,text]
-----------------
INFO: Operating system name: Linux version: 6.11.0-109019-tuxedo architecture: amd64
INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 17.0.14+7-Ubuntu-124.04
INFO: Memory limit heap: 1024mb non-heap: 0mb
INFO: Character encoding: US-ASCII
INFO: Version: 6.6
INFO: Starting server...
INFO: HikariPool-1 - Starting...

INFO: Set default schema name to PUBLIC
INFO: Creating database history table with name: PUBLIC.DATABASECHANGELOG

INFO: Table tc_attributes created

INFO: Foreign key constraint added to tc_device_command (deviceid)

INFO: New row inserted into tc_servers
INFO: ChangeSet changelog-4.0-clean::changelog-4.0-clean::author ran successfully in 214ms

INFO: Index user_device_user_id created

INFO: Column tc_orders.toAddress renamed to toaddresstmp

INFO: UPDATE SUMMARY
INFO: Run:                         50
INFO: Previously run:               0
INFO: Filtered out:                 0
INFO: -------------------------------
INFO: Total change sets:           50

INFO: Update summary generated

INFO: Started Server@c18dcc4{STARTING}[11.0.24,sto=0] @4926ms

INFO: Stopping server...

INFO: Version: 6.6
INFO: Starting server...

INFO: UPDATE SUMMARY
INFO: Run:                          0
INFO: Previously run:              50
INFO: Filtered out:                 0
INFO: -------------------------------
INFO: Total change sets:           50
-----------------

Note that the second start is faster, since the database is already there -
which is exactely what we wanted.


==== debugging

We are creating traccar client software without modifying the traccar server.
We are starting the traccar server docker image out of the box 
to develop against it (and save a lot of mocking etc.).

One way to check the server is the `tracker-server.log`.
As one example you can debug one of 
the `bm.traccar.api.*IT` integration tests.
Most of them `extend BaseIntegrationTest` 
which uses the preconfigured system administrator to log in.

In the log you can see the system user id `9000000000000000000` 
creating users with ids `1` and `2` 

  INFO: user: 9000000000000000000, action: create, object: user, id: 1
  INFO: user: 9000000000000000000, action: create, object: user, id: 2
  INFO: user: 2, action: login,  from: 172.17.0.1
  INFO: user: 2, action: logout, from: 172.17.0.1
  INFO: user: 1, action: login,  from: 172.17.0.1
  INFO: user: 1, action: logout, from: 172.17.0.1

  INFO: user: 1, action: login, from: [0:0:0:0:0:0:0:1]    frontend
  INFO: user: 1, action: login, from: 127.0.0.1            JUnit !?


=== call the API

You can call the Rest APIs such as

----
curl http://0.0.0.0:8080/api/v3/pet/123
----

Which returns information about a pet.

You can also update an existing PET such:

----
curl -XPUT -H "Content-Type: application/json" --data "@daisy.json" http://0.0.0.0:8080/api/v3/pet
----


=== login into fresh traccar server

  http://localhost/?token=VIRTUAL_ADMIN_ACCESS
  http://localhost/settings/user/9000000000000000000

=== grab JSESSIONID 

    wscat -c ws://localhost:80/api/socket -H "Cookie: JSESSIONID=node014ro3l06ueuxuvmvrcbykfbqp12.node0"

    Connected (press CTRL+C to quit)
    < {"positions":[]}
    < {}
    Disconnected (code: 1006, reason: "")   // trigger: docker:run > CTRL+C

=== enter browser request

    https://demo3.traccar.org/api/devices?id=1461
    https://demo3.traccar.org/api/devices/1461





















