
:toc:

= Database Testing

After setting up the Traccar Docker Container there are different options to set up the database
according to your development focus. The Database (ERM) can be perceived as the backdoor
through which you can peek into the data and analyze the actions of your integration tests.

Multiple options for handling the H2 database are scribbled here, 
including mounting external volumes, direct SQL shell access. 
Kind of a cheat sheet outlining different database introspection approaches 
for development and testing.

== database introspection

The recommended traccar docker installation is to leave the database inside the container.

Yet by mounting the `/data` folder we can look inside the data, which stays persistent
after the container has stopped - at development time.
You can find the `data` mount line in the `docker-maven-plugin`
and un/comment as required:

    <volumes>
        <bind>
            <volume>/opt/traccar/data:/opt/traccar/data:rw</volume>

[TIP]
====
The H2 database is locked 
as long the traccar container is working for its simplicity. +
Developers can debug `*IT` tests running against the traccar container +
and exit the test after a scenario has been setup. +
Then the docker container must be stopped in order to use the h2 shell.
====

https://www.baeldung.com/java-h2-db-execute-sql-file[h2 access]
    


== `h2.tools.Shell`
 
You can always inspect `h2` through its console,
as a back door directly the database model. 
The default h2 database is ideal, i.e. made for testing.
Developers can login to the traccar data base, explore the schema 
and inspect data with `plain SQL`, reset to scratch .. whatever is feasible for you.

You will find the database in your filesystem 
in `/opt/traccar/data` as specified above. 
The following command line assumes to be in this folder.

Then you need to install the h2 lib and point to the jar

    /opt/traccar/data$ java -cp /opt/h2/bin/h2-2.3.232.jar org.h2.tools.Shell 
                            -url jdbc:h2:./database 
                            -user sa
                            
and you should get a welcome
    
    Welcome to H2 Shell 2.3.232 (2024-08-11)
    Exit with Ctrl+C

and start querying

  sql> select id, name, email, hashedpassword, salt from tc_users;

  ID | NAME    | EMAIL  | HASHEDPASSWORD                                   | SALT
  1  | admin   | admin  | 44e0c0902fd515f49884c4fd9b78cbabfc7237586a7bc921 | a9d60a6a1734e06c5d76294404e536e8713369d877423d8e
  2  | newUser | email  | null                                             | null
  7  | user2   | email2 | 53e175f9ded19f065d7e483f44f540f7f8ca9c4026dd69dd | 72e2e2555df4a62c2d8ccb8fb295f7d19dc9373cfdf51772


== `h2.tools.RunScript`

    java -cp /path/to/h2/jar/h2-version.jar org.h2.tools.RunScript
         -url jdbc:h2:db/server/url
         -user sa -password password
         -script script.sql
         -showResults

== `h2.tools.Console`

You can run a console, which opens a database frontend in your browser

    java -cp /opt/traccar.bak/h2/bin/h2-2.3.232.jar org.h2.tools.Console 
         -web 
         -tcp 
         -url jdbc:h2:./database 
         -user sa


== database available / locked

  docker:run

  $ java -cp /opt/traccar/h2/bin/h2-2.3.232.jar org.h2.tools.Shell 
         -url jdbc:h2:/opt/traccar/data/database 
         -user sa
  Exception in thread "main" org.h2.jdbc.JdbcSQLNonTransientConnectionException:
    Database may be already in use: "/opt/traccar/data/database.mv.db".
    Possible solutions: close all other connection(s); use the server mode [90020-232]
  Caused by: org.h2.mvstore.MVStoreException:
    The file is locked: /opt/traccar/data/database.mv.db [2.3.232/7]

     stop container

  sql> delete from tc_users where id=2;
  Error: org.h2.jdbc.JdbcSQLNonTransientException:
  The database is read only; SQL statement: delete from tc_users [90097-232]

    -> change access to database* files
    $ sudo chmod 777 database*
    => works :)


== hashing the password

https://www.traccar.org/forums/topic/hashing-the-password/

[source,xml]
----
    # generate a random salt
    salt="$(dd if=/dev/urandom bs=24 count=1 status=none | xxd -p)"
    
    # generate the password hash from the contents of the "password" variable 
    (which you've to set yourself to the new cleartext password)
    hash="$(openssl-3.0.1 kdf -keylen 24 -binary -kdfopt digest:sha1 
          -kdfopt "pass:$password" -kdfopt "hexsalt:$salt" -kdfopt iter:1000 pbkdf2 | xxd -p)"
    
    # uncomment the following line to print out both the salt and the password hash
    #echo -e "salt: $salt\nhash: $hash"
    
    # set the value of "tchome" to the path of the Traccar directory
    tchome="/opt/traccar"
    
    # and finally update the password (and salt) of the default "admin" user
    java -cp "$tchome/lib/h2-"*".jar" org.h2.tools.Shell 
         -url "jdbc:h2:$tchome/data/database" 
         -user sa 
         -sql "update tc_users set hashedpassword='$hash', salt='$salt' 
               where email = 'admin';"
----




== sql with Maven

    https://github.com/kbeigl/jeets/blob/master/jeets-models/pom.xml

            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2database-version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.dbunit</groupId>
                <artifactId>dbunit</artifactId>
                <version>${dbunit-version}</version>
                <scope>test</scope>
            </dependency>

