
:toc:

= traccar-openapitools-client

The complete Traccar REST API is defined in a single `openapi.yaml` file 
and its first line defines the `openapi: 3.1.0` specification.
This file is used with the  
link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator] 
to generate a plain Java Client from an 
link:https://swagger.io/specification/[OpenAPI specification]. 
The generator is controlled and configured via 
link:https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin[openapi-generator-maven-plugin] 
and produces a `traccar-api-generated-x.y.z.jar` (in two steps).

== tl;dr

This project is actually only holding the `openapi-traccar-x.y.z.yaml` file as source 
and is used to generate a child project in the `target/` folder and 
run this child project to produce the `traccar-api-generated-x.y.z.jar`.

In a `clean` state you can not see the child project and actually 
there is no need to open this `traccar-openapitools-client` project
nor the created child project in your IDE to avoid extra configuration (for a not existing project).
Once the Java Client is created and stored in your `.m2` repository 
it will be picked up by higher layer projects, i.e. the `traccar-api-client`.

== client abstraction

Since 
link:https://www.openapis.org/[OpenAPI is an official specification] 
there are many and will be more different code generators.
Anyhow the resulting functionalities should remain the same.
Therefore our client development will not directly invoke the server calls on the generated artifact.
The higher level `traccar-api-client` is wrapped around the generated client (hiding it!),
yet abstracting the server invocations with the `bm.traccar.api.Api interface`.

== download `openapi.yaml` file

The complete Traccar REST API is defined in a single `openapi.yaml` file 
to be found in the root folder of every release.
The `latest` version is available at the + 
*(1)* 
link:https://www.traccar.org/api-reference[Official Traccar API Reference] 
by clicking the button "Download OpenAPI specification". +
or *(2)* 

    https://www.traccar.org/api-reference/openapi.yaml

or *(3)* 

    https://raw.githubusercontent.com/traccar/traccar/master/openapi.yaml

or *(4)* for older versions you can use the version tag at github, i.e.

    https://github.com/traccar/traccar/blob/v6.7.1/openapi.yaml

For the time being we will download the specification to the project resources:

    <inputSpec>${project.basedir}/src/main/resources/openapi-traccar-${traccar.version}.yaml</inputSpec>

and to be on the safe side we rename the source to a specializing name

    openapi-traccar-6.7.1.yaml
    openapi-traccar-${traccar.version}.yaml

to apply the `${traccar.version}` of the Maven `bm-traccar` branch 
and to raise a fail fast for bad versioning. 

TODO: This process could be automated. 
i.e. download and parse `openapi.yaml` for actual values.

== openapi-generator-maven-plugin

When you run `mvn compile`, the Maven lifecycle passes the `generate-sources` phase. 
The plugin is configured to participate in that phase, 
and executes the Maven Plugin with the given configuration.

[source,xml]
----
    <id>generate-client</id>
    <goals>
        <goal>generate</goal>
    </goals>
----

You can identify these tags in the build output: 

    openapi-generator-maven-plugin:7.13.0:generate (generate-client)
                                          ========  ===============

During the `compile` phase, all the code generated 
from the grammar files is compiled without further configuration. +
You can check the 
link:https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-maven-plugin/README.md[General Configuration parameters]
for all options.

Basically we use the `java` generator with the `restclient` library

[source,xml]
----
    <configuration>
        <inputSpec>${project.basedir}/src/main/resources/ 
                        openapi-traccar-${traccar.version}.yaml</inputSpec>
        <generatorName>java</generatorName>
            <configOptions>
                <library>restclient</library>
            </configOptions>
----

and we define several package names to generate
                            
[source,xml]
----
        <invokerPackage>bm.traccar.invoke</invokerPackage>
            <apiPackage>bm.traccar.generated.api</apiPackage>
          <modelPackage>bm.traccar.generated.model.dto</modelPackage>
----

and we specify the artifact to be generated, i.e. the versioned name of the `jar`:

[source,xml]
----
           <groupId>bm</groupId>
        <artifactId>traccar-api-generated</artifactId>
----
                        
To keep things simple we do not post process (`JAVA_POST_PROCESS_FILE`)
the result nor do we use the `--model-name-mappings` - as of now. 
Anyhow it is a good place to adopt the model to your company model.

=== two step processing

By running `mvn install` on project level

    ~/git/bm/bm-traccar/traccar-openapitools-client$ mvn install

you can idenfify the processing in two steps.

=== step 1 - traccar-openapitools-client


[source,text]
-----------------
[INFO] --- openapi-generator-maven-plugin:7.13.0:generate (generate-client) 
  :                                          @ traccar-openapitools-client ---
[INFO] OpenAPI Generator: java (client)
  :
[INFO] Processing operation null
-----------------
This is raised because the traccar yaml file does not provide `operationId` for endpoints. +
Then the *DTO* are created in the `target/generated-sources/openapi` folder:

[source,text]
-----------------
[INFO] writing file .../openapi/src/main/java/bm/traccar/generated/model/dto/Attribute.java
     generated project: openapi                generated DTOs in folder: dto
-----------------

If you look into the *newly generated `openapi/` project* you will find a completly generated maven project,
which you can not find in the original sources.
The `openapi` project comes with a lengthy `pom.xml` 
with the name and group we have defined earlier to define the final `jar` outputted.

Then the generator creates an `operationId` for every endpoint:

[source,text]
-----------------
[WARNING] Empty operationId found for path: get /devices. 
     Renamed to auto-generated operationId: devicesGet
                               =======================
-----------------

These are used to create `api/` sources, tests and markdown docs 

[source,text]
-----------------
[INFO] writing file /openapi/src/main/java/bm/traccar/generated/api/AttributesApi.java
[INFO] writing file /openapi/src/test/java/bm/traccar/generated/api/AttributesApiTest.java
[INFO] writing file /openapi/docs/AttributesApi.md              ===
-----------------

and finally the project generation is wrapped up with 

[source,text]
-----------------
[INFO] writing file /openapi/pom.xml
  :
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/ApiClient.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/ServerConfiguration.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/ServerVariable.java
  :
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/JavaTimeFormatter.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/StringUtil.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/auth/HttpBasicAuth.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/auth/HttpBearerAuth.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/auth/ApiKeyAuth.java
  :
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/auth/Authentication.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/RFC3339DateFormat.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/RFC3339InstantDeserializer.java
[INFO] writing file /openapi/src/main/java/bm/traccar/invoke/RFC3339JavaTimeModule.java
  :
-----------------

The rest of the maven build for _this project_ is irrelevant:

[source,text]
-----------------
[INFO] --- maven-compiler-plugin:3.1:compile     (default-compile) ---
[INFO] Not compiling main sources
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) ---
[INFO] No sources to compile
[INFO] --- maven-surefire-plugin:3.5.3:test      (default-test) ---
[INFO] No tests to run.
[INFO] --- maven-jar-plugin:2.4:jar              (default-jar) ---
[INFO] Building jar: traccar-openapitools-client-6.7.1.jar
-----------------

This is achieved with 

    <maven.main.skip>true</maven.main.skip>

as there are no sources to process and test.

=== step 2 - traccar-api-generated

So we have generated a new maven project `traccar-api-generated` +
in the `target/generated-sources/openapi` folder - and not a client software - yet.

The newly generated project is not part of any predefined POM.
To handle this we add the `exec-maven-plugin` to execute a complete `mvn install`
to provide the generated jar for further processing.
The execution is bound to the `install` phase

[source,xml]
----
    <id>install-generated-client</id>
    <phase>install</phase>
    <goals>
        <goal>exec</goal>
    </goals>
----

which you can find in the build process

[source,text]
-----------------
[INFO] --- exec-maven-plugin:3.5.0:exec (install-generated-client) 
                                               @ traccar-openapitools-client ---
[INFO] ----------------------< bm:traccar-api-generated >----------------------
[INFO] Building traccar-api-generated 6.7.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] --- maven-enforcer-plugin:3.4.0:     .. @ traccar-api-generated ---
[INFO] --- build-helper-maven-plugin:3.4.0: .. @ traccar-api-generated ---
[INFO] --- maven-resources-plugin:2.6:      .. @ traccar-api-generated ---
[INFO] --- maven-compiler-plugin:3.11.0:    .. @ traccar-api-generated ---
[INFO] --- build-helper-maven-plugin:3.4.0  .. @ traccar-api-generated ---
[INFO] --- maven-resources-plugin:2.6:      .. @ traccar-api-generated ---
[INFO] --- maven-compiler-plugin:3.11.0:    .. @ traccar-api-generated ---
[INFO] --- maven-surefire-plugin:3.1.2:     .. @ traccar-api-generated ---
[INFO] --- maven-jar-plugin:3.3.0:jar       .. @ traccar-api-generated ---
[INFO] Building jar: .../openapi/target/traccar-api-generated-6.7.1.jar
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:     .. @ traccar-api-generated ---
[INFO] --- maven-jar-plugin:3.3.0:          .. @ traccar-api-generated ---
[INFO] Building jar: .../openapi/target/traccar-api-generated-6.7.1-tests.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:3.5.0:jar   .. @ traccar-api-generated ---
[INFO] Building jar: .../openapi/target/traccar-api-generated-6.7.1-javadoc.jar
[INFO] 
[INFO] --- maven-source-plugin:3.3.0:       .. @ traccar-api-generated ---
[INFO] Building jar: .../openapi/target/traccar-api-generated-6.7.1-sources.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:        .. @ traccar-api-generated ---
[INFO] Installing   .../openapi/target/traccar-api-generated-6.7.1.jar 
       to   .../.m2/repository/bm/traccar-api-generated/6.7.1/traccar-api-generated-6.7.1.jar
-----------------

Note that the execution is triggered in the first project: `@ traccar-openapitools-client` + 
to launch the `Building` of the generated project: `@ traccar-api-generated`.

As you can see several `jar` files are being built and finally installed in your `.m2/repository`.
Once the `traccar-api-generated-x.y.z.jar` is installed this project has served its purpose 
and only needs to be rerun for a new traccar release.

Another thing worth mentioning is that you will get an internal `BUILD SUCCESS` 
for the Maven execution kicked off from the main lifecycle:

[source,text]
-----------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.498 s
[INFO] Finished at: 2025-06-16T13:51:22+02:00
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.282 s
[INFO] Finished at: 2025-06-16T13:51:22+02:00
[INFO] ------------------------------------------------------------------------
-----------------

=== javadocs

*After* generating the `traccar-openapitools-client` you can access 
link:./target/generated-sources/openapi/target/apidocs/index.html[the javadocs]
directly in the `generated-sources/` folder.

Of course they will be lost again after a `mvn clean`, 
but then you still have the `traccar-api-generated-6.7.1-javadoc.jar` in your `.m2`!

== conclusion

This project should be a closed shop in the best case.
Meaning that it is used to invoke a fully automated generation +
of a REST Client Software `traccar-api-generated-x.y.z.jar` +
from the (renamed) traccar specification `openapi-traccar-x.y.z.yaml` file.

Of course you can code on the basis of this `jar`,
but it is recommended to use the higher level `traccar-api-client` project,
which provides the `Api interface` and embeds the Java Client
in a Spring `@Service` for simple handling and integration.
