:toc: left

== Traccar API Implementation

This software is based on a generated *Java Spring REST Client* from the Traccar REST specification.
The single package (`bm.traccar.api`) implementation wraps the Java client in a *Spring* @Service
to be applied wherever feasible. The API client completely hides the REST intricities
inside regular Java methods.

The `traccar-api-client` is basically a single package application or rather _service_. +
In addition there is a websocket package to receive live information from the Tracking System.


== openapi-generator

As Traccar provides a REST specification in form of a `yaml` file we faciliate the 
link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator]

[quote, see github.com/OpenAPITools/openapi-generator]
____
OpenAPI Generator allows generation of API client libraries (SDK generation), 
server stubs, documentation and configuration automatically 
given an OpenAPI Spec v3.
____

Note that this Java code generation takes place in the isolated 
xref:../../traccar-openapitools-client/openapitools.adoc[`traccar-openapitools-client`] 
project. It has to run before this project which is build around the generated artifact.

[TIP]
====
To get more details on the generation you can read the project notes:
xref:../../traccar-openapitools-client/openapitools.adoc[openapitools-client]
====

You can check 
link:https://ademico-software.com/how-to-generate-the-client-api-for-an-openapi-rest-service/[Generate the client using Maven] 
for a starting point on how to apply Maven properties etc.


== Traccar REST

Traccar `v6.7` provides *17 APIs* (see `package bm.traccar.generated.api`)
and as the GTS progresses + 
Traccar `v6.12.2` provides *19 APIs*.
These APIs support many aspects of GPS Tracking and beyond, like health monitoring.

The `traccar-api-client` defines _one single (nested) API interface:_ 
`bm.traccar.api.Api`, which allows us to switch the implementation.
This was required, for example, when changing from swagger to OpenAPI (3 to 3.1). +

[TIP]
====
Therefor you should stick to the `bm.traccar.api.Api interface` 
to connect your program logic!
====

=== Data Transfer Objects - DTOs ...

In addition the `traccar-api-client-6.7` provides *21 Data Transfer Objects* +
and `v6.12.2` already has 26 (package `bm.traccar.generated.model.dto`).

These DTO _represent_ the different System Entities 
and are used to exchange information with the server. +
For example the User API call to 
link:https://www.traccar.org/api-reference/#tag/Users/paths/~1users/post[Create a User] 
is provided as Java method by the Api interface:

[source,java]
----
    public interface Api {
           interface Users {
                User createUser(User user) throws ApiException;
----

In your code you can easily create a `new User()` in your software 

[source,java]
----
    User userIN = new User();
    userIN.setName(usr);
    userIN.setEmail(mail);
    userIN.setPassword(pwd);
    userIN. ...
----
    
and  then create it on server side and receive a copy:

[source,java]
----
    User userOUT =  api.users.createUser(userIN);
----

Note that `userIN` and `userOUT` are different instances,
i.e. `userIN` on client and `userOUT` is returned from server.
The latter provides the `userId` provided by the Traccar Model
and is vital to use in the client server communication.
The ID is usually hidden for external users (i.e. in the UI),
but required for unambiguously user identification!

=== ... are not System Entities

Nevertheless you should always distinguish _Data Transfer Objects_
from actual Entities in the Systems _Entity Relations Model_ - ERM.
_The Traccar System_ is build around the _Traccar Data Model_,
which is represented in the 
link:https://github.com/traccar/traccar/tree/master/src/main/java/org/traccar/model[model package],
while the DTOs are created in the
link:https://github.com/traccar/traccar/tree/master/src/main/java/org/traccar/api/resource[resource package].
The Entities are only accessed by Traccar itself, while DTOs are snapshots of them.
The Traccar Database is the best place to monitor what's going on.

This is similar to DNA and RNA: +
The DNA (ERM) is part of the _living_ organic System, +
while the RNA (DTOs) is simply a copy of the DNA from a certain point in time.


== Traccar sub Api implementations

This project is part of a larger software and therefor the Traccar Api Endpoints (`operationId`)
are implemented in the order required by the main application.
During prototyping you should _avoid_ any bulk implementations.
Protoyping is modelling and every new cycle, i.e. `x.y.z release` 
can introduce new sub APIs and endpoints - as the main application progresses.
This way the implementation for all sub APIs turns into a mature pattern.
And interdependencies can be implemented with convenient methods combining common actions. 

The most important aspect of this project is its _layer functionality_.
As the Traccar GTS progresses the REST specification is modified 
and we want to avoid code changes all over our application.
In the best case the code changes can be restricted to this project.
The project can fix and hide specification inconsistencies 
and should provide consistent Java methods.

[TIP]
====
This page is about architecture and usage of the Traccar OpenAPI Client. +
If you are looking for the usage of the Traccar API and sub APIs +
you can go directly to the 
xref:./api/traccar-api.adoc[Traccar API page].
====

== Traccar `ApiAspect` and `ApiException`

This API client implementation applies _Aspect-Oriented Programming_ (*AOP*) 
as the technique for handling exceptions in Spring Boot applications. 
This way all exception handling happens in one central `ApiAspect` class 
and avoids code duplication.

We apply AOP, since the Traccar REST API is a moving target.
SubAPIs are added, methods and types are changed etc.
With AOP we can grasp a general pattern that applies to _all_ sub APIs,
even the ones we haven't implemented or Traccar will offer in future.

Generally any problem in the client software should through an `ApiException` 
to take over responsibility and to provide useful messages for developers 
and wrap the cause for deeper analysis.

As you can see in the `bm.traccar.api.ApiAspect` class 
the `@Pointcut` includes all `*Api` classes and methods in :

      @Pointcut("execution(public * bm.traccar.generated.api.*Api.*(..))")

and the `Joinpoint` is defined to only catch `RestClientExceptions`,
wrap them in an `ApiException` and throw it for the method execution:

  public void afterThrowingApiMethod(JoinPoint joinPoint, RestClientException rcEx)
      throws ApiException {

Note that the `ApiException` is a `RuntimeException` and 
the caller is not forced by the compiler to catch it.
However you should handle it as good practice
and to ensure that you have a binding communication.

[source,java]
-----------------
    Spring AOP
    invocation order
        invoke **UsersApi.usersPost(..) ** <-------------+
          invoke ApiClient.selectHeaderAccept(..)        |
          invoke ApiClient.selectHeaderContentType(..)   |
          invoke ApiClient.invokeAPI(..)                 |
        Exception in ApiMethod: **UsersApi.usersPost(..) **
-----------------

