
:toc:

= Traccar Client Development

The `bm-traccar` module, i.e. Maven subbranch, is the development environment 
to code against the link:https://www.traccar.org/[Traccar GPS Tracking Platform].
Traccar is a GPS Tracking System (GTS) written in Java and published as Open Source Software.
The System was thoroughly analyzed in the 
link:https://github.com/kbeigl/jeets/blob/master/README.adoc[Jeets Project]
and
link:https://github.com/kbeigl/jeets/blob/master/README.adoc#literature[Jeets Book].

This module defines the Traccar version for all submodules

        <traccar.version>6.7.1</traccar.version>

Please read the following instructions to get the most out of your development.


== Dockerized Traccar Server

The Traccar Client Software is developed with Integration Tests against a Docker Traccar Server.

link:./dox/dockerSetup.adoc[Read on to fetch, build and run the Traccar docker container ...]

== Database handling

After setting up the Traccar Docker Container there are different options to set up the database
according to your development focus. The Database (ERM) can be perceived as the backdoor
through which you can peek into the data and analyze the actions of your integration tests.

link:./dox/databaseTest.adoc[read more ...]

