:toc: left

== ci/cd workflows 

We are using GitHub as our version control system and GitHub Actions for our CI/CD pipeline. +
You can find the workflows in the `.github/workflows/` files of this repo.


Dotfiles are text-based configuration files (e.g. `.gitignore`) for Unix-like systems, +
named after the "." prefix that hides them. 
[IMPORTANT]
====
Make sure you have set your file browser tool to show hidden files.
====

Dotfiles are also part of this repository to serve various purposes.


=== `.github/workflows/`

This directory contains the YAML files for GitHub Actions, which automate workflows for the repository.

`https://github.com/kbeigl/bm/actions`

NOTE: `java-version: '21'` is currently hardcoded in both files


=== `build.yml`

This workflow is triggered on every push or pull request to the main branches. +
Its primary role is to build the project and run tests to ensure code quality and integration.

The GitHub Build is intentionally kept simple with as little tools as possible.
While doing a full fledged development against a Docker Container with Integration Testing,
the cloning and compiling of the jar files should be kept simple.

Therefore we are using the commandline

[source,xml]
----
      - name: Build with Maven (excluding integration tests and doc generation)
        run: |
          ./mvnw -B -ntp install \
            --file pom.xml \
            -Dintegration.tests.skip=true \
            -Ddocker.skip.tests=true \
            -Dopenapi.skip=false \
            -Dasciidoc.process.skip=true
----

to apply the `skip` switches 

- to turn off Docker and Integrationtests 
- to turn off the generation of documentation and diagrams

Note that the generation of the openapi client is turned ON,
since it is _absolutely required_ for compilation and testing.
Anyhow developers should set the switch to TRUE after generating the client _once_.
This guarantees that the client is accessible in the local Maven repo.

As the output on GitHub is extremly long due to the logging of downloads
we apply 

    -ntp (--no-transfer-progress) 
    
to suppress Downloading, Downloaded, and Progress transfer lines. +
And `-B` for CI-friendly non-interactive output

Also note that we are explicitly calling the wrapper `./mvnw` of the project +
and not the `mvn` command with unforeseeable version.


If you have problems with a local Maven build you can always check 
the building and testing logs for every push to the repository.

[TIP]
====
If you clone and build the project locally and run into problems +
please check the  
https://github.com/kbeigl/bm/actions[latest builds on GitHub].
====


=== releases

A GitHub release is essentially just a Git tag with some release notes and attached binary files (called "assets").
Because it's agnostic to the Maven build tool, GitHub is used to run a Maven build 
and then attach the generated JAR files as assets to the release.

A Maven multi-module project is made for development in different teams, but it can be released as a single unit. 
Anyhow every module can be released independently, which is a great advantage for the development process.
Also a good architecture provides individual modules for different layers, 
which can be released and used independently.

For example the `traccar-openapitools-client` can be used independently in any Java project, 
without the need to use the `traccar-api-client` or `traccar-realtime-client` and
without any strings attached to the rest of this project.

The `release.yml` workflow will perform the following steps:

    1. Call the build workflow (`build.yml`) as a reusable subprocedure to compile, test, and upload the build artifacts.
    2. Check out the repository's code.
    3. Download the built JAR artifacts.
    4. Create a new GitHub release associated with the tag.
    5. Upload the JAR files as assets to the newly created release.

The Release process is triggered by pushing a new Git tag to the repository, 
which can be done manually or through the GitHub UI when creating a release.

Note that 'GitHub Pages' is also a build-release mechanism.

=== `release.yml`

This workflow automates the release process. 
It is triggered when a new version tag (e.g., `v1.0.0`) is pushed. 
The workflow builds the project, creates a new GitHub release, 
and attaches the generated JAR files as release assets.

[TIP]
====
If you hesitate to clone and build the project locally 
and rather would like to have some demo JAR files to play with,
you should check the latest 
https://github.com/kbeigl/bm/releases[release on GitHub]
====

More information about each module, library, CLI can be found 
in the sections marked with *Download* or *Quickstart*.


=== Maven Wrapper 

The Maven Wrapper is a script that allows you to run a specific version of Maven 
without requiring users to install it manually. 
The `.mvn/wrapper/maven-wrapper.properties` file specifies the version of Maven to use and the distribution URL to download it from. +

// === `.gitignore` 
// todo (locate existing descriptions)


