:toc: left
:toclevels: 5
:doctype: book

= The gps Timer

We have created the `Gpx2OsmandParser` as a sample ETL for other GPS sources. +
With the `List<MessageOsmand>` we have defined the Target Format for the `PlayerOsmAnd`. +
Now we need to take care to actually _play_ this list of messages forming the track.
Besides sending the messages in the correct, i.e. chronological order,
we need to create a solid Timer Component to send messages at precise times.


After we have the messages in the right format, we need to take care 
of the timing of the sending from a `gps-tracker`.
We are using the  `GpsPlayerIT` as out dev environment similar to the `GpsTrackerIT` .

As a starting point we define the Player API with the following method:

[source,java]
----
      public synchronized boolean playOsmAndTrack() {
----

Note that the method is synchronized to ensure thread safety when multiple trackers are involved. 
And be aware that the player is already loaded with the track messages from the parser.
We can define the method signature and call it from the test, 
while the implementation of the timer will be added step by step. 
The method will be responsible for scheduling the sending of messages based on their timestamps.

The actual player implementation is similar to the parser design with Camel +
with *(1)* a route invoking *(2)* a bean method:

*(1)* We are using a  `PlayerTimerRoute` to send messages to the timer component

[source,java]
----
public class PlayerTimerRoute extends RouteBuilder {

  @Override
  public void configure() {
    from("quartz://" + ...
            :
            // room for additional parameters (trigger, job store, misfire handling, .. ) 
            :
            .bean("quartzSchedulerBean", "sendCurrentAndScheduleNext");
----

with the Consumer Endpoint URI `"quartz://" + . . .` for the Camel Quartz component +
which eventually will trigger the sending of messages to the Producer Endpoint 

*(2)* the bean method `sendCurrentAndScheduleNext` in the `QuartzSchedulerBean` class.

This player design is the separation of concerns between the timer route and +
the scheduling logic in the bean, which will finally schedule and send the messages:

        player.tracker.sendMessage(MessageOsmand message);


== Implementation

The `PlayerOsmAnd` is designed analogously, _not hierarchical_ to the  `TrackerOsmAnd` 

- with a Camel Route to deal with external technologies via their endpoints 
- and a Spring Bean as the entry to the Spring Framework 

This simplicity becomes helpful while the framework is still evolving. +
The intended interaction of the tracker and player becomes apparent in the following code snippet:

[source,java]
----
    TrackerOsmAnd tracker = new TrackerOsmAnd();
     PlayerOsmAnd player  = new  PlayerOsmAnd();

    player.loadTrack(gpxSource);
    player.setTracker(tracker);
    player.playOsmAndTrack(track);
      -->  tracker.sendMessage(message);
----

Idealy we want to analyze a _past scenario_ (`fromTime`-`toTime`) with a number of trackers. +

- [ ] Then we can create a single interface to *playback the scenario* and +  
      *control the playback* (pause, resume, speed factor) for all trackers at once. 

Think of a complex traffic scenario with multiple vehicles, +
where we want to find out who caused a traffic jam and how it evolved over time. +
Provided we can access crowd sourced GPS data 
of many vehicles, in a certain area and time frame.


== Requirements

To implement the scheduling of messages based on their timestamps, we need to:

- [x] Iterate through the `List<MessageOsmand>` in chronological order.
- [x] For each message, calculate the *time difference* to the previous message.
- [x] Use the calculated *time difference to schedule* the next message to be sent after that delay.

Ensure that the scheduling is done in a way that allows for pausing and resuming +
the playback of the track, as well as adjusting the speed of playback if needed.

Technically, _we do not want_ a blocking (`while`)  loop (in every tracker ! ), but rather +
a non-blocking way to schedule _only_ the next message after the previous one has been sent.


=== Camel Timer vs Quartz

As we are working with Camel and Spring, 
https://camel.apache.org/components/timer-component.html[Camel's Timer]
 would be a preconfigured choice. +
But the Camel Timer with periodic events at fixed intervals is not made to fire at specific, 
predetermined timestamps from a list. 
This could be achieved by calculating the delay for each message and using a `timer` endpoint with a  
https://camel.apache.org/components/eips/delay-eip.html[Delay EIP]. +
We'll keep it in mind as a (pure Camel EIP) fallback solution.

For a large realtime scenario we want to be able to level up on demand +
and rely on a more robust and feature-rich scheduling library. +
The 
https://www.quartz-scheduler.org/[_Quartz Enterprise Job Scheduling Library_] is fit for any scenario

[quote, see https://www.quartz-scheduler.org/]
____
Quartz is a richly featured, open source job scheduling library that can be integrated within virtually any Java application ...
Quartz can be used to create simple or complex schedules for executing tens, hundreds, or even tens-of-thousands of jobs ... 
The Quartz Scheduler includes many enterprise-class features ... +
Quartz is licensed under the Apache 2.0 license.
____

We'll go with Quartz that might better suit specific time-based triggers +
and add the 
https://camel.apache.org/components/4.18.x/quartz-component.html[`camel-quartz://`]
component to the project.


=== ad hoc Scheduling

To keep the player design flexible for enhancements, we want to *only schedule one message at a time* and one after another - *for each tracker*.
This way we can easily upgrade by adding features like pausing, resuming, 
or even introduce a time factor to speed up or slow down (or play backwards!) the playback of the track.

With Camel's Quartz component, you can create a route that schedules messages to be sent at specific times. +
Quartz triggers are typically defined at startup, but *not* in our use case! +
We need to schedule messages dynamically based on the consecutive timestamp in our message list.


=== Camel Quartz Consumer

If we look at the 
https://camel.apache.org/components/4.18.x/quartz-component.html[`camel-quartz://`]
documentation, we see that it is designed as a consumer component only, 
meaning it can trigger routes based on a schedule, 
but it does not provide a way to dynamically schedule messages at runtime. +
We can create a Quartz trigger with a specific start time for each message
 
    from("quartz://osmandTrackGroup/dynamicTrackJob?trigger.startAt=" + ...

but _we can not reuse the same trigger key for multiple starttimes_ (`trigger.startAt=`)

    TRIGGER_KEY = quartzGroup + "." + quartzJob

or we get:

    Failed to resolve endpoint: quartz://osmandTrackGroup/dynamicTrackJob
                                        ?trigger.startAt=Fri+May+29+16%3A23%3A58+CEST+2026
    due to:
                            Trigger key osmandTrackGroup.dynamicTrackJob
          is already in use by quartz://osmandTrackGroup/dynamicTrackJob
                                                        =

(note the difference of `.` vs `/` in the trigger key) +
and we can not easily update or remove triggers once they are created.
 

The error occurs because Quartz tries to register a trigger with the same name 
while the old trigger from the previous run is still registered in the scheduler.
Quartz does not allow duplicate trigger IDs within the same group by default.

It would be possible to create a new trigger for each message with a unique name,
but this could lead to _a really large number_ of triggers being created and managed by Quartz,
which is not efficient and can lead to performance issues.
And it requires additional logic to clean up old dangling triggers after they have fired, 
which adds complexity for a clean/ing implementation.

To resolve this, Quartz must be told to _update_ or _replace_ the existing trigger instead of creating a new one. +
Let's see how we can achieve this with Camel.


=== Camel Quartz Component

To work around this limitation, Camel  
allows us to access the underlying _Quartz Scheduler API_ directly. +
We can access it after start and pass it to the bean +
as you can see in `PlayerOsmAnd.ensurePlaybackRoutes()` method:
    
[source,java]
----
  quartzScheduler = new QuartzSchedulerBean(this, new TriggerKey(quartzJob, quartzGroup));
        :
  // Create/get Quartz component early so the scheduler is available before routes can fire.
  QuartzComponent quartzComponent = (QuartzComponent) camel.getComponent("quartz");
  quartzScheduler.setQuartzScheduler(quartzComponent.getScheduler());

  camel.addRoutes(new PlayerTimerRoute(quartzGroup, quartzJob, idSuffix));
  camel.start();
----

We are getting the Scheduler from the QuartzEndpoint, which is always reachable via the registered endpoint.
The QuartzComponent (and therefore _the native Scheduler_) is fetched before `camel.start()`. 
This prevents the `Quartz scheduler not set` warning that would otherwise appear 
in a narrow race condition between context start and the first explicit `playOsmAndTrack()` call.

Note that the route construction

[source,java]
----
  camel.addRoutes(new PlayerTimerRoute(quartzGroup, quartzJob, idSuffix));
----
    
is setting up the route with the same trigger key for all messages for each tracker,
by using the `uniqueId` as `idSuffix` to distinguish between different trackers 
and their quartz schedulers. 
Anyhow the quartz group and job allow scaling in a desired granularity.

[source,java]
----
  String idSuffix = sanitizeQuartzId(uniqueId);
  String quartzGroup = "osmandTrackGroup-" + idSuffix;
  String quartzJob   = "dynamicTrackJob-"  + idSuffix;
----


The route is setup with a trigger time in far future,
which will be overridden with the first message sent.

Each player has its own Quartz Scheduler and PlayerTimerRoute as default implementation!

