:toc: left
:toclevels: 5
:doctype: book

= The gpx Parser

For development we are using tracks recorded with a 
https://de.wikipedia.org/wiki/Buell_Lightning_XB12S[BUELL XB 12 STT] motorcycle
in the Bavarian Forest around Regensburg in Germany.

A sample track in the `resources` folder of this project
will be used for development and testing: +

  bm/bm-tracker/gps-osmand-player/src/test/resources/gpx/RGB-BUELL-SE-080607.gpx


[NOTE]
====
The parsing of the gpx file is not the main topic of this project. 
Therefor the `Gpx*.java` components are added to the `bm.gps` package
in the `bm.gps.gpx` sub package as a general helper to parse `*.gpx` files 
and create `MessageOsmand` messages with the help of the GeoTools library.
====

== The Model

The `gps-osmand-player` is designed to feed position updates into the `gps-osmand-tracker` component.
Therefore the Model is based on the `MessageOsmand` message 
which is the standard message format for position updates in the `gps-osmand-tracker`.

On a longer term we can think about a more generic model for position updates: +
An (abstract) `gps-player` to support any `gps-\*-tracker` +
acting as `gps-*-player` component with the `*` protocol.


== gpx Format

The `*.gpx` format is a common (well formed) `xml` format for GPS tracks and is supported by many GPS devices and software.
The file contains a list of `trkpt` elements with `lat`, `lon`, `ele` (elevation or altitude to sealevel) and (preferrably UTC) `time` stamps.

[source,xml]
----
        :
    <trkseg>
        :                                       calculate ..
      <trkpt lat="49.0310032" lon="12.1030925"> ---+      .. course, distance 
        <ele>319.7756348</ele>                     | --+          .. (slope) 
        <time>2008-06-07T09:08:55Z</time>          |   | ---+     .. and speed
      </trkpt>                                     |   |    |
      <trkpt lat="49.0309343" lon="12.1030384"> ---+   |    |
        <ele>319.2950439</ele>                      ---+    |
        <time>2008-06-07T09:10:27Z</time>                ---+
      </trkpt>
        :
----

which is exactly what we need to satisfy the minimum GPS requirements for the osmand protocol. +
As described earlier we can add calculated speed and course as we create the position updates.

[IMPORTANT]
====
By using the gpx format for development we are using a globally accepted xml format for gps tracks.
During prototyping with a small number of attributes we can do the reading and parsing ourselves.
In order to level up we can replace our code with the 
https://mvnrepository.com/artifact/org.geotools/gt-gpx/2.5.5[GeoTools gt-gpx module]
====


== gpx Route

As our first source for position updates we will use a `*.gpx` file as described above. +
Since we are using Spring and Camel we can easily apply the Camel `file://` component + 
to wire the file and create a Camel route to parse it to `MessageOsmand` messages.

Creating the initial Camel `"file: .."` route is straight forward:

[source,java]
----
  @Component
  public class GpxMessageRoute extends RouteBuilder {
        
    @Override
    public void configure() throws Exception {
        
      fromF("file:%s?include=%s", sendDirectory, include)
        .routeId("gpx-file-player")
        .process(
            exchange -> {
              File gpxFile = exchange.getIn().getBody(File.class);
              if (gpxFile == null) {
                throw new IllegalArgumentException(
                    "Unable to resolve GPX file from Camel file exchange");
              }
              exchange.getIn().setBody(gpxFile);
            })
            
        // java.io.File allocated for parsing ... 
----

This is the implementation of a Camel-based Route using the File Component. +
It polls from `${gps.player.send-directory}` folder for new `*.gpx` files.

From development and testing the `jeets-player` software we have learned that 
it is very helpful to run the player without further ado - to keep focus.
Therefor we have defined a `sendDirectory` and an `include` pattern `.*\\.gpx` to read gpx file/s from 
- as part of the project. 

Do not confuse this with source directories where _you_ store _your_ gpx files on _your_ system! +
This directory should not be modified, files left untouched.


=== `sendDirectory`

When talking about a directory we are always aware that a directory has an absolute path and a relative path. 
By using the Camel `RouteBuilder` we can create a folder if it does not exist. 
The `sendDirectory` is created at startup 

- In tests we can always use the `target/` folder to create the `sendDirectory` +
  which will be cleaned up by maven on each build. 

- When running the application from command line we can use the `./` folder of the `jar` file +
  and create a  `sendDirectory` subfolder there.

- In production, when the player.jar is part of a larger application the  `sendDirectory` +
  should be defined in the app.props. 
  
- For a fixed scenario with fixed tracks (like a showcase) +
  we can also use the `resources` folder and define the `sendDirectory` there.

An existing directory satifiies the requirement of the Camel `file://` component + 
to observe, poll, read `from` 

[source,java]
----
      fromF("file:%s? ...", sendDirectory)
----
    
The idea is to launch the player once and then simply drop `*.gpx` files into the `sendDirectory` to start the simulation.
The Camel route serves as an ingestion point for the file/s (and player) and
will pick them up for processing. 

==== `file://` tuning

As you can see in the documentation of the  
https://camel.apache.org/components/file-component.html[Camel file: component] +
there are a number of options to tune the behavior of the file consumer.

For `jeets` development we have used a 
https://github.com/kbeigl/jeets/blob/master/jeets-clients/jeets-device/src/main/java/org/jeets/device/LineParser.java[LineParser]
to feed the player with single position updates. +
This way we could easily interrupt the player by deleting the file.

This time we want to parse the `gpx` file as a whole to avoid longer lasting file allocations. +
Anyhow we want to receive feedback, if the file could not be parsed or if there was an error. +
This is achieved by using the `move` and `moveFailed` options:

    &move=parsed/${file:name}
    &moveFailed=error/${file:name}
    
When the file is parsed successfully it will be moved to a `parsed/` subfolder. +
When there is an error during parsing it will be moved to an `error/` subfolder. +
Note that the files are _moved_ and not _copied_ to avoid file allocations. +
The developer can easily check the `parsed` and `error` folders. 

Note that these actions are performed after parsing - we have not sent anything yet. +
Files can be gracefully released to relieve system resources. + 
The next route is technically separated and can make use of the tracker and send - possibly for hours.

=== output

The rest of the route is straight forward: 

- we direct the file body to a `parser` bean to parse the file +
  and create a `List<MessageOsmand> messages`
- we use the EIP `splitter` to split the list of messages +
  and send them one by one to the configurable `outputUri`

[source,java]
----
        // java.io.File allocated for parsing ... 
        .bean(parser, "parse")  // gpx File
        .split(body())          // List<MessageOsmand>
        .to(outputUri);         // MessageOsmand
    }
  }
----

The route automatically processes files into Osmand messages via `Gpx2OsmandParser`
and sends parsed messages to the configured `gps.player.output-uri` (seda queue in tests).)

== device id

Note that Traccar requires a device id for each device update.
Traccar (default) defines a fixed protocol for a fixed port and 
the `gps-osmand-tracker` implementation is based on the osmand protocol. 
And the device with a fixed device id 
must be registered in the Traccar server to receive the updates.
It is the vital reference ID to the Traccar Model and System.

On client side we have many options to define the device id.
In the context of gpx files we _can not_ simply add a new attribute,
as this de-standardizes the well defined file expected in standard geo software. 

We _can_ use (1) the track name, if it is present 

  <trk>
    <name>RGB-BUELL-SE-080607</name>

or (2) the file name as device id. +
It can be helpful to 'play' different files as different devices, vehicles
for observations on the Map. +
For more flexibility we will add (3) a property in the `app.props` +
and (4) a header constant as the fallback device id. 

Technically we could use one player with one tracker 
and transfer individual device ids with each position update.

=== `GpxPlayerHeaders`

The `GpxPlayerHeaders` class to provide an individual header for the device id
to be used as fallback in the route.

For name `GpxPlayerHeaders` should indicate that it can be used 
to inject more options for the player,

The `GpxToMessageOsmandParser`uses:

        •  track <name> as device id by default
        •  file name as fallback id


== `Gpx2OsmandParser`

The Java `@Component Gpx2OsmandParser` is a main processor of the route. +
With

[source,java]
----
        .bean(parser, "parse")
----

the `Gpx2OsmandParser.java` component's `parse` method is called +
and the return value passed to the next step in the route. +
The `parse` method basically does the following:

[source,java]
----
  public List<MessageOsmand> parse( File gpxFile, .. ) {
    Document document = parseDocument(gpxFile);
    List<GeoTools.TrackPoint> trackPoints = extractTrackPoints(document, gpxFile);    
----

with the help of the `GeoTools`, `org.w3c.dom` and `org.xml.sax` libraries.


=== `GeoTools.TrackPoint`

On the fly we have added a `GeoTools.TrackPoint` class to the `bm.gps.gpx` package + 
to represent the track points with timestamps. 

    record TrackPoint(double latitude, double longitude, long timestamp, Double altitude)
    
This Trackpoint is an important part of our GPS library for time & space evaluation. +
It can be used to calculate the course, distance, slope and speed 
between _two consecutive track points_.

Most importantly can be used by the `RealTimeController` (and other components) 
to validate the real-time behavior of the system 
- _independant of the source, format or protocol of the position updates_!
It serves as an abstraction layer for the real-time validation of the system.

===  `List<MessageOsmand>` 

The rest of the parse method creates a `MessageOsmand` for each track point
and returns the full list. 

[IMPORTANT]
====
The `Gpx2OsmandParser` returns the complete list of trackpoints of the complete `gpx` file. +
The breakdown to send single trackpoints to the output happens via splitter EIP in the route.
====


===  `GpxParseErrorHandler` 

The `GpxParseErrorHandler` was added to catch all the xml and sax stuff going on
and provide a usefull warning about the parsing problem with the file.
The SAX error handler was attached to the parser to catch malformed GPX XML 
and log it through SLF4J as a warning with file/line/column details
instead of the anonymous [Fatal Error] ... message.

[source,xml]
----
WARN  Gpx2OsmandParser - Malformed GPX XML
        in /home/kbeigl/git/bm/bm-tracker/gps-osmand-player/target/send/
        RGB-BUELL-SE-80608-INVALID.gpx at line 665, column 5:
            The end-tag for element type "trkpt" must end with a '>' delimiter.
----

Camel then logs the propagated exception as a route-processing failure,
which is why you still see the later DefaultErrorHandler stacktrace.
The remaining ERROR DefaultErrorHandler block is Camel logging the failed exchange, 
not the XML parser itself.
Also Camel’s noisy expected-error logging is reduced
while preserving the error/ move behavior.

[source,xml]
----
WARN  GenericFileOnCompletion - Rollback file strategy: 
      org.apache.camel.component.file.strategy.GenericFileRenameProcessStrategy@3b8366c8
      for file: GenericFile[/home/kbeigl/git/bm/bm-tracker/gps-osmand-player
                                        /target/send/RGB-BUELL-SE-80608-INVALID.gpx]
----

The `Gpx2OsmandParserTest` contains explicit unit tests for the `Gpx2OsmandParser`,
but you can also see the new warnings in other tests, with invalid files, for example. 


== `GpxMessageRouteTest`

This filesystem-based test verifies the functionality of the `GpxMessageRoute` end-to-end. +
After the route has started the method

[source,java]
----
  private void copyGpxFromSourceToInputAndAwait(String fileName) throws Exception {
    CopyFileRoute copyFileRoute = new CopyFileRoute(fileName, sourceDirectory, sendDirectory);
    copyFileRoute.copyAndAwait(camel, producer); // block until file is copied
  }
----

can be used to copy a `.gpx` file from any configurable sources folder 
to the `sendDirectory`. +
For copying ( _not moving !_ ) we have created a small helper route 
`bm.gps.gpx.file.CopyFileRoute` to drop a `*.gpx` file into the `sendDirectory` 
and await the parsed messages to arrive in the next line of the test. 

If the parsing was successful the file will be moved to a subfolder. +
And the route output, being single `MessageOsmand` messages, 
will be consumed from the `seda:output` queue. +
Each test can then collect a list of messages `List<MessageOsmand> messages` for validations:

    •  copy `RGB-BUELL-SE-080607.gpx` into the watched input directory
    •  verify 161 `MessageOsmand` messages are emitted
    •  check first/second/last message contents
    •  verify the file has been moved to the `parsed` subfolder
