:toc: left
:toclevels: 5
:doctype: book

= The gpx Parser

We have prototyped the `gps-osmand-tracker` with a simple protocol 
to transfer *space & time* information. 
Now we want to feed the tracker with real position updates from tracks recorded in `*.gpx` files.
For development of a GPX Parser we are using tracks recorded with a 
https://de.wikipedia.org/wiki/Buell_Lightning_XB12S[BUELL XB 12 STT] motorcycle
in the Bavarian Forest around Regensburg in Germany.

== The Model

The `gps-osmand-player` is designed to feed position updates into the `gps-osmand-tracker` component.
Therefore the Model is based on the `MessageOsmand` message 
which is the standard message format for position updates in the `gps-osmand-tracker`.

- [ ] On a longer term we can think about a more generic model for position updates: +
An (abstract) `gps-player` to support any `gps-\*-tracker` +
acting as `gps-*-player` component for the `*` protocol.


== gpx Format

The `*.gpx` format is a common (well formed) `xml` format for GPS tracks and is supported by many GPS devices and software.
The file contains a list of `trkpt` elements with `lat`, `lon`, `ele` (elevation or altitude to sealevel) and (preferrably UTC) `time` stamps.
That is precicely what we need to satisfy the minimum GPS requirements for the osmand protocol. 
As described earlier we can add calculated speed and course as we create the position updates.

[source,xml]
----
  <trk>
    <name>RGB-BUELL-SE-080607</name>
        :
    <trkseg>
        :                                       calculate ..
      <trkpt lat="49.0310032" lon="12.1030925"> ---+ .. course, distance 
        <ele>319.7756348</ele>                     | --+ .. (slope) 
        <time>2008-06-07T09:08:55Z</time>          |   | ---+ .. and speed
      </trkpt>                                     |   |    |
      <trkpt lat="49.0309343" lon="12.1030384"> ---+   |    |
        <ele>319.2950439</ele>                      ---+    |
        <time>2008-06-07T09:10:27Z</time>                ---+
      </trkpt>
        :
----


[IMPORTANT]
====
By using the gpx format for development we are using a globally accepted xml format for gps tracks.
During prototyping with a small number of attributes we can do the reading and parsing ourselves.
In order to level up we can replace our code with the 
https://mvnrepository.com/artifact/org.geotools/gt-gpx/2.5.5[GeoTools gt-gpx module]
====


== Message Route Test

Sometimes it makes sense to define a test even before (or for) the actual implementation. +
If the parsing was successful the file will be moved to a subfolder. +
And the route output, being single `MessageOsmand` messages, 
will be consumed from the `seda:output` queue. +
Each test can then collect a list of messages `List<MessageOsmand> messages` for validations:

    •  copy `RGB-BUELL-SE-080607.gpx` into the polled input directory
    •  verify 161 `MessageOsmand` messages are emitted
    •  check first/second/last message contents
    •  verify the file has been moved to the `parsed` subfolder

And we have created two files in the `src/test/resources/gpx` folder for testing: +

	•  `RGB-BUELL-SE-080607.gpx` - a valid gpx file with 161 track points
	•  `RGB-BUELL-SE-80608-INVALID.gpx` - an invalid gpx file with a malformed xml tag
	
that should result in the following directory structure in the `target` folder:

	+── send
	    +── error
	    │   └── RGB-BUELL-SE-80608-INVALID.gpx
	    +── parsed
	        └── RGB-BUELL-SE-080607.gpx


== gpx Parser

In the loader we have predefined the method

[source,java]
----
  private void loadAndStartPlayer(File gpxFile) {
    String configuredDeviceId = ... deviceId.trim();
    List<MessageOsmand> messages = parser.parse(gpxFile, configuredDeviceId);
                                          =====
    String uniqueId = messages.getFirst().id();
      :
----

First we check if the `deviceId` is configured in the `app.props` file. +
Then we call the `Gpx2OsmandParser` to parse the gpx file 
and return a list of `MessageOsmand` messages. +
Then the `Gpx2OsmandParser.java` component's `parse` method is called 
and the return value passed to the next step in the route. +
The `parse` method basically does the following:

[source,java]
----
  public List<MessageOsmand> parse( File gpxFile, .. ) {
                             =====
    Document document = parseDocument(gpxFile); 
    String deviceId = resolveDeviceId(document, gpxFile, configuredDeviceId);
    List<GeoTools.TrackPoint> trackPoints = extractTrackPoints(document, gpxFile);    
      :
----

create a `Document` from the gpx file with a `DocumentBuilderFactory` and `DocumentBuilder` +
with the help of the `GeoTools`, `org.w3c.dom` and `org.xml.sax` libraries.


=== Device ID

Note that Traccar requires a device id for each device update.
Traccar (default) defines a fixed protocol for a fixed port and 
the `gps-osmand-tracker` implementation is based on the osmand protocol. 
And _the device must be registered with a fixed deviceId_ 
in the Traccar server to receive the updates.
It is the vital reference ID to the Traccar Model and System.

On client side we have many options to define the device id.
In the context of gpx files we _can not_ simply add a new attribute,
as this de-standardizes the well defined file expected in standard geo software. 
So we will 

1. check if the `deviceId` is configured in the `app.props` file
   as `{gps.player.device-id}` and use it if present, 

2. otherwise use the track name 

  <trk>
    <name>RGB-BUELL-SE-080607</name>

3. or file name as device id 

This should ensure an automated unique device id for each gpx file.
It can be helpful to 'play' different files as different devices, vehicles
of a scenario for observations on the Map. 

- [ ] remove deviceId from `app.props` 
- [ ] describe vital difference of `deviceId` and `uniqueId` in the Traccar model


=== Geo Track Point

On the fly we have added a `GeoTools.TrackPoint` class to the `bm.gps.gpx` package + 
to represent the track points with timestamps. 

    record TrackPoint(double latitude, double longitude, long timestamp, Double altitude)
    
This Trackpoint is an important part of our GPS library for time & space evaluation. +
It can be used to calculate the course, distance, slope and speed 
between _two consecutive track points_.

Most importantly it will be used internally by the `RealTimeController` (and other `bm` components) 
to validate the real-time behavior of the system 
- _independant of the source, format or protocol of the position updates_!
It serves as an abstraction layer for the real-time validation of the system.


===  Message List 

[IMPORTANT]
====
The `Gpx2OsmandParser` returns + 
the complete list `List<MessageOsmand>` of trackpoints + 
of the complete `gpx` file. 
====


===  Parse Error 

The `GpxParseErrorHandler` was added to catch all the `xml` and `sax` stuff going on +
and provide a usefull warning about the parsing problem with the file.

[source,java]
----
    builder.setErrorHandler(new GpxParseErrorHandler(gpxFile));
----

The `SAX` error handler was attached to the parser to catch malformed `GPX XML` 
and log it through `SLF4J` + 
as a warning with file/line/column details
instead of the anonymous `[Fatal Error]` ... message.

[source,xml]
----
`sendInvalidGpxFile`

	WARN  Gpx2OsmandParser - Malformed GPX XML
	        in /home/kbeigl/git/bm/bm-tracker/gps-osmand-player/target/send/
	        RGB-BUELL-SE-80608-INVALID.gpx at line 665, column 5:
	        ------------------------------    --------  --------
	            The end-tag for element type "trkpt" must end with a '>' delimiter.
----

while a valid file will be parsed and logged as
	
`sendAndParseGpxFile`

	INFO  Gpx2OsmandParser - Parsed 161 track points from 'RGB-BUELL-SE-080607.gpx' file 
							   into 161 Osmand messages for deviceId 'RGB-BUELL-SE-080607'

Camel then logs the propagated exception as a route-processing failure,
which is why you still see the later DefaultErrorHandler stacktrace.
The remaining ERROR DefaultErrorHandler block is Camel logging the failed exchange, 
not the XML parser itself.
Also Camel’s noisy expected-error logging is reduced
while preserving the error/ move behavior.

[source,xml]
----
WARN  GenericFileOnCompletion - Rollback file strategy: 
      org.apache.camel.component.file.strategy.GenericFileRenameProcessStrategy@3b8366c8
      for file: GenericFile[/home/kbeigl/git/bm/bm-tracker/gps-osmand-player
                                        /target/send/RGB-BUELL-SE-80608-INVALID.gpx]
----

The `Gpx2OsmandParserTest` contains explicit unit tests for the `Gpx2OsmandParser`,
but you can also see the new warnings in other tests, with invalid files, as example. 


== load and start player

We can now get back to our predefined the method in pseudo code:

[source,java]
----
  private void loadAndStartPlayer(File gpxFile) {  
  
    // get List<MessageOsmand> messages
    // get uniqueId
	
	// check, if player( uniqueId ) already exists, then stop and remove it
	// create new PlayerOsmAnd 
		// check if tracker( uniqueId ) exists and is running
		// load the player with message list 
		
	// * start the playback *
	player.playOsmAndTrack()
----

That is the basic idea of how to load and start a player with a gpx file. +
In addition the loader keeps track of the 'players' 
in a `Map<String, PlayerOsmAnd>` to define the playback scenario.

Now we can get back to the `PlayerOsmAnd` class 
and see how the timing of the `playOsmAndTrack()` method is implemented.


include::gps-timer.adoc[lines=5..11]

xref:./gps-timer.adoc[goto Timer Implementation ...]







