spring.application.name=gps-osmand-tracker

traccar.host=http://localhost:80
# WebSocket is derived from host (+ port)

# traccar.name=admin
# traccar.password=admin
# traccar.email=admin@scenario.com

# port for tracker protocol osmand
# TODO -  USE DIFFERENT PORT THAN TRACCAR CLIENT PORT!
osmand.dcs=http://localhost:5055

traccar.server.registration=true

# Spring Configuration
# don't use ANSI colors in logs for easier copying
spring.output.ansi.enabled=never

# Camel Configuration
camel.springboot.main-run-controller=true
camel.main.run-controller=true

# logging levels
logging.level.org.springframework = INFO
# logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.apache.camel.spring.boot=DEBUG
# switch on for @Aspect dev etc.
# logging.level.bm.traccar.api = DEBUG
# logging.level.io.vertx=DEBUG
# logging.level.org.apache.camel.component.vertx=DEBUG
# logging.level.org.apache.camel=DEBUG
