package bm.traccar.api;

import static org.junit.jupiter.api.Assertions.assertEquals;

import bm.traccar.generated.model.dto.User;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Test <code>api/users</code> methods, @see <a
 * href="https://www.traccar.org/api-reference/#tag/Users">UsersApi</a> with ApiService. <br>
 * In database lingo create, update, delete User in traccar datamodel using generated entities.
 */
public class UsersApiIT extends BaseIntegrationTest {
  private static final Logger logger = LoggerFactory.getLogger(UsersApiIT.class);

  /** Test platonic API methods from interface for User DTO */
  @Test
  public void createUpdateDeleteUser() {

    api.setBearerToken(virtualAdmin);

    // get nr of users, assert users++, back to nr
    int userNr = api.getUsersApi().getUsers(null).size();

    // create / receive user
    User user = new User();
    // newUser.setId(5); // do not use!, generated by DB
    user.setName("user-1");
    user.setEmail("email-1"); // email syntax is not validated !
    user.setPassword("pw-1"); // can't login UI without a password (useful!), backend can without

    User newUser = api.getUsersApi().createUser(user);
    // matching method names !!
    assertEquals(userNr + 1, api.getUsersApi().getUsers(null).size());

    // returns the generated id (asserts not null)
    Long userId = newUser.getId();

    // update user
    newUser.setEmail("email-1-b");

    User putUser = api.getUsersApi().updateUser(userId, newUser);
    assertEquals(userNr + 1, api.getUsersApi().getUsers(null).size());

    // delete user
    api.getUsersApi().deleteUser(putUser.getId());
    assertEquals(userNr, api.getUsersApi().getUsers(null).size());
  }

  /**
   * Due to API (generated code) inconsistency the id is Long here, but restricted to Integer range.
   * Values out of Integer range will throw an ApiException and the server is not called (and must
   * not be running for test).
   */
  @Test
  public void doNotUpdateDeleteUser() {

    api.setBearerToken(virtualAdmin);
    User user = new User(); // won't reach server
    // Long values out of Integer range will throw an ApiException
    Long longUserId = (long) (Integer.MAX_VALUE + 1L);

    // update user should fail without server call
    try {
      api.getUsersApi().updateUser(longUserId, user);
    } catch (ApiException e) {
      assertEquals(ArithmeticException.class, e.getCause().getClass());
    }
    logger.error("User with id={] was not updated on server!", longUserId);

    // delete user should fail without server call
    try {
      api.getUsersApi().deleteUser(longUserId);
    } catch (ApiException e) {
      assertEquals(ArithmeticException.class, e.getCause().getClass());
    }
    logger.error("User with id={] was not deleted on server!", longUserId);
  }

  @Test
  public void convertLongToInt() {

    // positive test
    Long longVal = 12345L;
    Integer intVal = ApiHelper.toInt(longVal);
    assertEquals(longVal, 12345L);

    // negative test
    longVal = Integer.MAX_VALUE + 1L;
    try {
      intVal = ApiHelper.toInt(longVal);
    } catch (ApiException e) {
      assertEquals(ArithmeticException.class, e.getCause().getClass());
    }
    logger.error("Long value {} was not converted to Integer!", longVal);
  }
}
