
:toc:

= repository content and structures

This repository serves as development environment +
for the `The RealObject Application Framework` +
outlined in this 
link:https://www.amazon.com/Programming-GPS-OpenStreetMap-Applications-Java-ebook/dp/B00OD4AUQ8[book].

== latest versions

[source,text]
-----------------
[INFO] === blue marble simulations       === 1.1.9-SNAPSHOT
[INFO] --- blue marble parameters        --- 1.1.9-SNAPSHOT
[INFO] ---- traccar client implementations - 1.1.9-SNAPSHOT
[INFO] ..... traccar-openapitools-client     6.8.0 ........ 
[INFO] ..... traccar-api-client              6.8.0 ........ 
[INFO] ..... traccar-rt-client               6.8.0 ........ 
-----------------

For earlier versions check the 
xref:releases.adoc[version history] 

== `/bm-parent`

This `bm-sim` repository is a *Maven Multi Module* project.
The Maven Reactor mechanism makes sure to collect all modules 
and assert correct build order with every `mvn` command executed. 
It assures that any project is build as required by another.  

xref:../../bm-parent/src/asciidoc/bm-parent.adoc[details ...]


== `/bm-traccar`

The `bm-traccar` aggregator POM is the development environment 
to code against the link:https://www.traccar.org/[Traccar GPS Tracking Platform].
Traccar is a GPS Tracking System (GTS) written in Java and published as Open Source Software.
The System was thoroughly analyzed in the 
link:https://github.com/kbeigl/jeets/blob/master/README.adoc[Jeets Project]
and
link:https://github.com/kbeigl/jeets/blob/master/README.adoc#literature[Jeets Book].

xref:../../bm-traccar/src/asciidoc/bm-traccar.adoc[read more to setup and adopt your development environment]

As of `v1.1.8` we are developing the following three 
cascaded and yet independent artifacts:


=== 1. `traccar-openapitools-client`

The Traccar REST API is defined in a single `openapi.yaml` file,
which is processed with the  
link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator] 
to generate a plain Java Client `traccar-api-generated-x.y.z.jar` from the 
link:https://swagger.io/specification/[OpenAPI specification]. 

xref:../../bm-traccar/traccar-openapitools-client/src/asciidoc/openapitools.adoc[details ...]

=== 2. `traccar-api-client`

==== The Traccar OpenAPI Client

The `traccar-api-client` is a Java Client Software to provide full (remote) control over your Traccar server.
And it can be used to integrate your Tracking with your company systems, 
like Human Resources-, Sales- and Fleet Management Software.
Synchronize your employees with their cars and driver information without utilizing the traccar UI.
Pull driving reports for your sales team ... and much more ;) 

xref:../../bm-traccar/traccar-api-client/src/asciidoc/traccar-api-client.adoc[details ...]

=== 3. `traccar-rt-client`

==== The Traccar Real-Time Client

The traccar-rt-client is a Java Client Software 
to provide full (remote) control over and interact 
via live surveillance of your Traccar Server Scenario. 

xref:../../bm-traccar/traccar-rt-client/src/asciidoc/traccar-rt-client.adoc[details ...]

