
:toc:

= repository content and structures

This repository serves as development environment +
for the  
link:https://www.amazon.com/Programming-GPS-OpenStreetMap-Applications-Java-ebook/dp/B00OD4AUQ8[`The RealObject Application Framework`]

== latest versions

[source,text]
-----------------
    [INFO] === blue marble simulations               === 1.1.16 
    [INFO] --- blue marble parameters                --- 1.1.16 
    [INFO] ---- GPS Trackers                         --- 1.1.16 
    [INFO] ..... gps-osmand-tracker          1.1.16 ........... 
    [INFO] ---- Traccar Clients                      --- 1.1.16 
    [INFO] ..... traccar-openapitools-client 6.10.0 ........... 
    [INFO] ..... traccar-api-client          6.10.0 ........... 
    [INFO] ..... traccar-realtime-client     6.10.0 ........... 
-----------------

For earlier versions check the 
xref:releases.adoc[version history] 

== `/bm-parent`

This `bm-sim` repository is a *Maven Multi Module* project.
The Maven Reactor mechanism makes sure to collect all modules 
and assert correct build order with every `mvn` command executed. 
It assures that any project is build as required by another. 

If you are not sure about your Maven Version it is highly recommended to use the 
xref:../../bm-parent/src/asciidoc/maven-maintenance.adoc[Maven Wrapper]   
in the root directory! +
If you modify the versioning make sure the build order matches the listing above.
Otherwise the Maven Reactor has detected inconsistencies.

xref:../../bm-parent/src/asciidoc/bm-parent.adoc[bm-parent details ...]


== `/bm-tracker`

This `bm-tracker` branch is used to develop _virtual GPS Tracker Simulators_ +
which can track real things by sending their positions frequently.

For the ROAF development we want to start bottom up.
[IMPORTANT]
====
*All Devices in the ROAF provide GPS coordinates _(lat,lon,fix)_*
====
as a common basis for Framework development. 

The ROAF vision described in the book is based on simple and platonic rules. +
In order to simulate things, events and interactions of the real world, 
we will need _a grid for space and time_. +
With respect to the blue marble we might speak of _Globe Positioning_.


=== Traccar Trackers

In the long run we want to be able to create scenarios with any or all 
https://www.traccar.org/devices/[devices] and
https://www.traccar.org/protocols/[protocols] implemented in traccar. 

=== The 'JeeTS Tracker'

If the Traccar Trackers don't fit your business the 
link:https://github.com/kbeigl/jeets/blob/master/README.adoc#literature[JeeTS Book]
you demonstrates how to create Protocols with Message Catalogs to fit your business, 
how to integrate your own Tracker with the traccar platform and your business model.

xref:../../bm-tracker/src/asciidoc/bm-tracker.adoc[more about GPS and Tracking ...]


=== `gps-osmand-tracker`

==== The GPS OsmAnd Tracker

The first ROAF GPS Tracker will serve as a placeholder for more customized trackers.
We will look at the standard components of a Tracking Device 
and implement the most simple Tracker by using the public `OsmAnd` protocol.
You can find the protocol specs  
link:https://www.traccar.org/osmand/[here], 
xref:OsmAndProtocolSpecification.adoc[here] and elsewhere.

xref:./../../bm-tracker/gps-osmand-tracker/src/asciidoc/gps-osmand-tracker.adoc[goto gps-osmand-tracker project]


== `/bm-traccar`

The `bm-traccar` aggregator POM is the development environment 
to code against the link:https://www.traccar.org/[Traccar GPS Tracking Platform].
Traccar is a GPS Tracking System (GTS) written in Java and published as Open Source Software.
The System was thoroughly analyzed in the 
link:https://github.com/kbeigl/jeets/blob/master/README.adoc[JeeTS Project]
and
link:https://github.com/kbeigl/jeets/blob/master/README.adoc#literature[JeeTS Book].

xref:../../bm-traccar/src/asciidoc/bm-traccar.adoc[read more to setup and adopt your development environment]

As of `v1.1.8` we are developing the following three 
cascaded and yet independent artifacts:


=== `traccar-openapitools-client`

The Traccar REST API is defined in a single `openapi.yaml` file,
which is processed with the  
link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator] 
to generate a plain Java Client `traccar-api-generated-x.y.z.jar` from the 
link:https://swagger.io/specification/[OpenAPI specification]. 

xref:../../bm-traccar/traccar-openapitools-client/src/asciidoc/openapitools.adoc[details ...]

=== `traccar-api-client`

==== The Traccar OpenAPI Client

The `traccar-api-client` is a Java Client Software to provide full (remote) control over your Traccar server.
And it can be used to integrate your Tracking with your company systems, 
like Human Resources-, Sales- and Fleet Management Software.
Synchronize your employees with their cars and driver information without utilizing the traccar UI.
Pull driving reports for your sales team ... and much more ;) 

xref:../../bm-traccar/traccar-api-client/src/asciidoc/traccar-api-client.adoc[details ...]

=== `traccar-realtime-client`

==== The Traccar Real-Time Client

The traccar-rt-client is a Java Client Software 
to provide full (remote) control over and interact 
via live surveillance of your Traccar Server Scenario. 

xref:../../bm-traccar/traccar-realtime-client/src/asciidoc/traccar-realtime-client.adoc[details ...]

xref:../../bm-traccar/traccar-realtime-client/src/asciidoc/traccar-rt-CLI.adoc[Quickstart]

