
:toc:

= repository content and structures

This repository serves as development environment +
for the `The RealObject Application Framework` +
outlined in this 
link:https://www.amazon.com/Programming-GPS-OpenStreetMap-Applications-Java-ebook/dp/B00OD4AUQ8[book].

== latest versions

[source,text]
-----------------
    [INFO] === blue marble simulations            === 1.1.10-RC 
    [INFO] --- blue marble parameters             --- 1.1.10-RC 
    [INFO] ---- traccar client implementations    --- 1.1.10-RC 
    [INFO] ..... traccar-openapitools-client 6.10.0 ........... 
    [INFO] ..... traccar-api-client          6.10.0-RC ........
    [INFO] ..... traccar-rt-client           6.10.0-RC ........ 
-----------------

For earlier versions check the 
xref:releases.adoc[version history] 

== `/bm-parent`

This `bm-sim` repository is a *Maven Multi Module* project.
The Maven Reactor mechanism makes sure to collect all modules 
and assert correct build order with every `mvn` command executed. 
It assures that any project is build as required by another.  

xref:../../bm-parent/src/asciidoc/bm-parent.adoc[details ...]


== `/bm-traccar`

The `bm-traccar` aggregator POM is the development environment 
to code against the link:https://www.traccar.org/[Traccar GPS Tracking Platform].
Traccar is a GPS Tracking System (GTS) written in Java and published as Open Source Software.
The System was thoroughly analyzed in the 
link:https://github.com/kbeigl/jeets/blob/master/README.adoc[Jeets Project]
and
link:https://github.com/kbeigl/jeets/blob/master/README.adoc#literature[Jeets Book].

xref:../../bm-traccar/src/asciidoc/bm-traccar.adoc[read more to setup and adopt your development environment]

As of `v1.1.8` we are developing the following three 
cascaded and yet independent artifacts:


=== `traccar-openapitools-client`

The Traccar REST API is defined in a single `openapi.yaml` file,
which is processed with the  
link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator] 
to generate a plain Java Client `traccar-api-generated-x.y.z.jar` from the 
link:https://swagger.io/specification/[OpenAPI specification]. 

xref:../../bm-traccar/traccar-openapitools-client/src/asciidoc/openapitools.adoc[details ...]

=== `traccar-api-client`

==== The Traccar OpenAPI Client

The `traccar-api-client` is a Java Client Software to provide full (remote) control over your Traccar server.
And it can be used to integrate your Tracking with your company systems, 
like Human Resources-, Sales- and Fleet Management Software.
Synchronize your employees with their cars and driver information without utilizing the traccar UI.
Pull driving reports for your sales team ... and much more ;) 

xref:../../bm-traccar/traccar-api-client/src/asciidoc/traccar-api-client.adoc[details ...]

=== `traccar-realtime-client`

==== The Traccar Real-Time Client

The traccar-rt-client is a Java Client Software 
to provide full (remote) control over and interact 
via live surveillance of your Traccar Server Scenario. 

xref:../../bm-traccar/traccar-rt-client/src/asciidoc/traccar-rt-client.adoc[details ...]

=== CLI Quick Start

After creating the three layers around the `ApiClient`, `Api interface` 
and `RealTimeManager` these are combined 
in the `@SpringBootApplication  RealTimeClient`.

==== run `RealTimeClient` CLI

The `traccar-rt-client` does not provide any webservices.
It is a plain command line interface (CLI) to connect to a traccar server 
from the command line and read what's going on.

    @SpringBootApplication
    public class RealTimeClient implements CommandLineRunner

Therefor it is a solid building block for real time applications.
You can integrate it in your application and code against the
`RealTimeManager` as if it was the traccar server.


pick up the `traccar-rt-client-6.10.0-RC.jar`

put it in `/someFolder/traccar-rt-client-6.10.0-RC.jar`

(release url)

copy app.props

enter credentials

run java, mvn spring:run ..

start your traccar client or your tracker connected to traccar

watch the console over the map

If you don't have a traccar server you can sign up 
at one of traccar's demo servers.

RealTimeClient is a Spring Boot application that:

    •  Starts RealTimeController on launch.
    •  Reads admin credentials from application.properties.
    •  Logs in as the admin user when starting.
    •  Remains running until manually shutdown (e.g., Ctrl+C), and supports graceful shutdown.

  modify RealTimeClient to a @SpringBootApplication that starts the RealTimeController
  and log in as traccar.admin.name as provided in the application.properties and can be gracefully shutdown manually

  You can run the application as usual (e.g., with mvn spring-boot:run or java -jar),
  and it will log in and initialize the real-time controller using the configured admin credentials.





