
:toc:

= repository content and structures

This repository serves as development environment +
for the `The RealObject Application Framework` +
outlined in this 
link:https://www.amazon.com/Programming-GPS-OpenStreetMap-Applications-Java-ebook/dp/B00OD4AUQ8[book].

== latest versions

[source,text]
-----------------
    [INFO] === blue marble simulations               === 1.1.14 
    [INFO] --- blue marble parameters                --- 1.1.14 
    [INFO] ---- traccar client implementations       --- 1.1.14 
    [INFO] ..... traccar-openapitools-client 6.10.0 ........... 
    [INFO] ..... traccar-api-client          6.10.0-RC ........ 
    [INFO] ..... traccar-realtime-client     6.10.0-RC ........ 
    [INFO] ---- GPS Unit and Tracker                 --- 1.1.14 
    [INFO] ..... gps-osmand-tracker          1.1.14-POC  ......
-----------------

For earlier versions check the 
xref:releases.adoc[version history] 

== `/bm-parent`

This `bm-sim` repository is a *Maven Multi Module* project.
The Maven Reactor mechanism makes sure to collect all modules 
and assert correct build order with every `mvn` command executed. 
It assures that any project is build as required by another. 

If you are not sure about your Maven Version
it is highly recommded to use the 
xref:../../bm-parent/src/asciidoc/maven-maintenance.adoc[Maven Wrapper]   
in the root directory!


xref:../../bm-parent/src/asciidoc/bm-parent.adoc[bm-parent details ...]


== `/bm-traccar`

The `bm-traccar` aggregator POM is the development environment 
to code against the link:https://www.traccar.org/[Traccar GPS Tracking Platform].
Traccar is a GPS Tracking System (GTS) written in Java and published as Open Source Software.
The System was thoroughly analyzed in the 
link:https://github.com/kbeigl/jeets/blob/master/README.adoc[Jeets Project]
and
link:https://github.com/kbeigl/jeets/blob/master/README.adoc#literature[Jeets Book].

xref:../../bm-traccar/src/asciidoc/bm-traccar.adoc[read more to setup and adopt your development environment]

As of `v1.1.8` we are developing the following three 
cascaded and yet independent artifacts:


=== `traccar-openapitools-client`

The Traccar REST API is defined in a single `openapi.yaml` file,
which is processed with the  
link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator] 
to generate a plain Java Client `traccar-api-generated-x.y.z.jar` from the 
link:https://swagger.io/specification/[OpenAPI specification]. 

xref:../../bm-traccar/traccar-openapitools-client/src/asciidoc/openapitools.adoc[details ...]

=== `traccar-api-client`

==== The Traccar OpenAPI Client

The `traccar-api-client` is a Java Client Software to provide full (remote) control over your Traccar server.
And it can be used to integrate your Tracking with your company systems, 
like Human Resources-, Sales- and Fleet Management Software.
Synchronize your employees with their cars and driver information without utilizing the traccar UI.
Pull driving reports for your sales team ... and much more ;) 

xref:../../bm-traccar/traccar-api-client/src/asciidoc/traccar-api-client.adoc[details ...]

=== `traccar-realtime-client`

==== The Traccar Real-Time Client

The traccar-rt-client is a Java Client Software 
to provide full (remote) control over and interact 
via live surveillance of your Traccar Server Scenario. 

xref:../../bm-traccar/traccar-realtime-client/src/asciidoc/traccar-realtime-client.adoc[details ...]

xref:../../bm-traccar/traccar-realtime-client/src/asciidoc/traccar-rt-CLI.adoc[Quickstart]

== `/bm-tracker`

The Maven project branch `bm-traccar` serves as the development environment for integrating with the Traccar GPS Tracking Platform. 
We have created a `traccar-realtime-client` to mirror what's going on in the Tracking System.
This `bm-tracker` branch is used to develop GPS Tracker Simulators which can track things by sending their positions frequently.

xref:../../bm-tracker/src/asciidoc/bm-tracker.adoc[details ...]


=== `gps-osmand-tracker`

==== The GPS OsmAnd Tracker

The gps-osmand-tracker is a Java Client Software 
to simulate a standard device that collects GPS locations, 
optionally buffer and send them to a server asap. 

xref:./../../bm-tracker/gps-osmand-tracker/src/asciidoc/gps-osmand-tracker.adoc[goto `gps-osmand-tracker`]



