name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (excluding integration tests and doc generation)
        run: ./mvnw install
          --file pom.xml
          -Dintegration.tests.skip=true
          -Ddocker.skip.tests=true
          -Dopenapi.skip=false
          -Dasciidoc.process.skip=true
